using System.Collections.Generic;
using WinForge.Models;

namespace WinForge.Catalog;

/// <summary>
/// 音訊效果目錄 · Catalog of ~40 ffmpeg-backed audio effects for the Audacity-style editor, rendered as
/// a searchable list of TweakCards. Every effect runs on the editor's current clip and swaps the result in.
/// All strings bilingual (English · 粵語).
/// </summary>
public static class AudioEffectsOperations
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== amplitude (8) =====
        AudioEffectTweak.Filter("audio.fx.gain-up-6", "Amplify +6 dB", "放大 +6 dB",
            "Boost the whole clip by 6 decibels.", "將成段加大 6 分貝。",
            "Apply", "套用", "volume=6dB", "amplify,gain,louder,volume,放大,音量,增益"),
        AudioEffectTweak.Filter("audio.fx.gain-up-3", "Amplify +3 dB", "放大 +3 dB",
            "Boost the whole clip by 3 decibels.", "將成段加大 3 分貝。",
            "Apply", "套用", "volume=3dB", "amplify,gain,louder,volume,放大,音量"),
        AudioEffectTweak.Filter("audio.fx.gain-down-3", "Attenuate -3 dB", "減弱 -3 dB",
            "Reduce the whole clip by 3 decibels.", "將成段減細 3 分貝。",
            "Apply", "套用", "volume=-3dB", "attenuate,quieter,gain,volume,減弱,音量"),
        AudioEffectTweak.Filter("audio.fx.gain-down-6", "Attenuate -6 dB", "減弱 -6 dB",
            "Reduce the whole clip by 6 decibels.", "將成段減細 6 分貝。",
            "Apply", "套用", "volume=-6dB", "attenuate,quieter,gain,volume,減弱,音量"),
        AudioEffectTweak.Filter("audio.fx.normalize", "Normalize loudness (EBU R128)", "正規化響度 (EBU R128)",
            "Even out perceived loudness to a broadcast target with loudnorm.", "用 loudnorm 將響度拉到廣播標準。",
            "Normalize", "正規化", "loudnorm=I=-16:TP=-1.5:LRA=11", "normalize,loudness,loudnorm,r128,正規化,響度"),
        AudioEffectTweak.Filter("audio.fx.peak-normalize", "Peak normalize", "峰值正規化",
            "Bring the loudest peak up to just below 0 dBFS.", "將最大峰值推到接近 0 dBFS。",
            "Normalize", "正規化", "dynaudnorm=p=0.95", "peak,normalize,dynaudnorm,峰值,正規化"),
        AudioEffectTweak.Filter("audio.fx.compress", "Compressor", "壓縮器",
            "Tighten dynamic range so quiet and loud parts sit closer together.", "壓窄動態範圍，大細聲更平均。",
            "Apply", "套用", "acompressor=threshold=-18dB:ratio=4:attack=20:release=250", "compress,dynamics,壓縮,動態"),
        AudioEffectTweak.Filter("audio.fx.limiter", "Limiter", "限幅器",
            "Hard-limit peaks to prevent clipping.", "硬性限制峰值，防止削波。",
            "Apply", "套用", "alimiter=limit=0.95", "limiter,limit,clip,限幅,削波"),

        // ===== fades & silence (6) =====
        AudioEffectTweak.Filter("audio.fx.fade-in-1", "Fade in (1 s)", "淡入 (1 秒)",
            "Add a one-second fade-in at the start.", "喺開頭加一秒淡入。",
            "Apply", "套用", "afade=t=in:st=0:d=1", "fade,fade in,淡入"),
        AudioEffectTweak.Filter("audio.fx.fade-in-3", "Fade in (3 s)", "淡入 (3 秒)",
            "Add a three-second fade-in at the start.", "喺開頭加三秒淡入。",
            "Apply", "套用", "afade=t=in:st=0:d=3", "fade,fade in,淡入"),
        AudioEffectTweak.Raw("audio.fx.fade-out-1", "Fade out (1 s)", "淡出 (1 秒)",
            "Add a one-second fade-out at the very end.", "喺結尾加一秒淡出。",
            "Apply", "套用", "-i {in} -af \"areverse,afade=t=in:st=0:d=1,areverse\" -c:a pcm_s16le {out}", "fade,fade out,淡出"),
        AudioEffectTweak.Raw("audio.fx.fade-out-3", "Fade out (3 s)", "淡出 (3 秒)",
            "Add a three-second fade-out at the very end.", "喺結尾加三秒淡出。",
            "Apply", "套用", "-i {in} -af \"areverse,afade=t=in:st=0:d=3,areverse\" -c:a pcm_s16le {out}", "fade,fade out,淡出"),
        AudioEffectTweak.Filter("audio.fx.trim-silence", "Trim leading/trailing silence", "剪走頭尾靜音",
            "Remove silence at the start and end of the clip.", "去走開頭同結尾嘅靜音。",
            "Trim", "剪裁", "silenceremove=start_periods=1:start_silence=0.1:start_threshold=-50dB:detection=peak,areverse,silenceremove=start_periods=1:start_silence=0.1:start_threshold=-50dB:detection=peak,areverse", "silence,trim,quiet,靜音,剪裁"),
        AudioEffectTweak.Filter("audio.fx.pad-silence", "Add 1 s silence at start", "開頭加 1 秒靜音",
            "Prepend one second of silence.", "喺開頭加一秒靜音。",
            "Apply", "套用", "adelay=1000|1000", "pad,silence,delay,靜音,延遲"),

        // ===== pitch & speed (8) =====
        AudioEffectTweak.Filter("audio.fx.speed-1_5", "Speed up 1.5×", "加速 1.5 倍",
            "Play 1.5× faster without changing pitch.", "用唔變音高嘅方式快 1.5 倍。",
            "Apply", "套用", "atempo=1.5", "speed,tempo,faster,加速,速度"),
        AudioEffectTweak.Filter("audio.fx.speed-2", "Speed up 2×", "加速 2 倍",
            "Play twice as fast without changing pitch.", "用唔變音高嘅方式快一倍。",
            "Apply", "套用", "atempo=2.0", "speed,tempo,faster,加速,速度"),
        AudioEffectTweak.Filter("audio.fx.speed-0_75", "Slow down 0.75×", "減慢 0.75 倍",
            "Play slower without changing pitch.", "用唔變音高嘅方式慢落嚟。",
            "Apply", "套用", "atempo=0.75", "speed,tempo,slower,減慢,速度"),
        AudioEffectTweak.Filter("audio.fx.speed-0_5", "Slow down 0.5×", "減慢 0.5 倍",
            "Play at half speed without changing pitch.", "用唔變音高嘅方式慢一半。",
            "Apply", "套用", "atempo=0.5", "speed,tempo,slower,減慢,速度"),
        AudioEffectTweak.Filter("audio.fx.pitch-up", "Pitch up +2 semitones", "升音 +2 半音",
            "Raise the pitch by two semitones, keeping duration.", "升高兩個半音，時長不變。",
            "Apply", "套用", "asetrate=44100*1.122462,aresample=44100,atempo=0.891", "pitch,semitone,up,升音,音高"),
        AudioEffectTweak.Filter("audio.fx.pitch-down", "Pitch down -2 semitones", "降音 -2 半音",
            "Lower the pitch by two semitones, keeping duration.", "降低兩個半音，時長不變。",
            "Apply", "套用", "asetrate=44100*0.890899,aresample=44100,atempo=1.122", "pitch,semitone,down,降音,音高"),
        AudioEffectTweak.Filter("audio.fx.chipmunk", "Chipmunk (pitch up octave)", "花栗鼠 (升八度)",
            "Raise pitch by a full octave for a chipmunk voice.", "升高一個八度，變花栗鼠聲。",
            "Apply", "套用", "asetrate=44100*2,aresample=44100", "pitch,octave,chipmunk,花栗鼠,八度"),
        AudioEffectTweak.Filter("audio.fx.deep", "Deep voice (pitch down octave)", "低沉 (降八度)",
            "Lower pitch by a full octave for a deep voice.", "降低一個八度，變低沉聲。",
            "Apply", "套用", "asetrate=44100*0.5,aresample=44100", "pitch,octave,deep,低沉,八度"),

        // ===== EQ & tone (8) =====
        AudioEffectTweak.Filter("audio.fx.bass-boost", "Bass boost", "加重低音",
            "Lift the low frequencies.", "提升低頻。",
            "Apply", "套用", "bass=g=8", "bass,eq,low,低音,等化"),
        AudioEffectTweak.Filter("audio.fx.bass-cut", "Bass cut", "減低音",
            "Reduce the low frequencies.", "減少低頻。",
            "Apply", "套用", "bass=g=-8", "bass,eq,low,低音,等化"),
        AudioEffectTweak.Filter("audio.fx.treble-boost", "Treble boost", "加重高音",
            "Lift the high frequencies for more sparkle.", "提升高頻，更通透。",
            "Apply", "套用", "treble=g=8", "treble,eq,high,高音,等化"),
        AudioEffectTweak.Filter("audio.fx.treble-cut", "Treble cut", "減高音",
            "Reduce the high frequencies.", "減少高頻。",
            "Apply", "套用", "treble=g=-8", "treble,eq,high,高音,等化"),
        AudioEffectTweak.Filter("audio.fx.highpass", "High-pass 100 Hz (remove rumble)", "高通 100 Hz (除隆隆聲)",
            "Cut very low frequencies to remove rumble/hum.", "切走超低頻，去走隆隆聲。",
            "Apply", "套用", "highpass=f=100", "highpass,rumble,hum,高通,隆隆"),
        AudioEffectTweak.Filter("audio.fx.lowpass", "Low-pass 12 kHz (soften hiss)", "低通 12 kHz (柔化嘶聲)",
            "Cut very high frequencies to soften hiss.", "切走超高頻，柔化嘶聲。",
            "Apply", "套用", "lowpass=f=12000", "lowpass,hiss,低通,嘶聲"),
        AudioEffectTweak.Filter("audio.fx.telephone", "Telephone EQ", "電話聲 EQ",
            "Band-limit to a tinny telephone sound.", "限頻做電話般嘅薄聲。",
            "Apply", "套用", "highpass=f=300,lowpass=f=3400", "telephone,bandpass,radio,電話,頻帶"),
        AudioEffectTweak.Filter("audio.fx.loudness-contour", "Loudness contour", "響度等化曲線",
            "Gently lift bass and treble for a fuller sound at low volume.", "輕微提升低高頻，細聲都飽滿。",
            "Apply", "套用", "bass=g=4,treble=g=3", "loudness,contour,eq,等化,響度"),

        // ===== effects (8) =====
        AudioEffectTweak.Filter("audio.fx.echo", "Echo", "回音",
            "Add a repeating echo tail.", "加重複嘅回音尾。",
            "Apply", "套用", "aecho=0.8:0.88:60:0.4", "echo,回音"),
        AudioEffectTweak.Filter("audio.fx.reverb", "Reverb (room)", "混響 (房間)",
            "Add a small-room reverb.", "加細房間嘅混響。",
            "Apply", "套用", "aecho=0.8:0.9:40|55|70:0.4|0.3|0.2", "reverb,room,echo,混響,房間"),
        AudioEffectTweak.Filter("audio.fx.reverb-hall", "Reverb (hall)", "混響 (大廳)",
            "Add a big-hall reverb.", "加大廳般嘅混響。",
            "Apply", "套用", "aecho=0.8:0.9:500|700|900:0.5|0.4|0.3", "reverb,hall,echo,混響,大廳"),
        AudioEffectTweak.Filter("audio.fx.denoise", "Noise reduction (FFT)", "降噪 (FFT)",
            "Reduce broadband background noise/hiss.", "減少背景雜訊／嘶聲。",
            "Reduce", "降噪", "afftdn=nr=12:nf=-25", "noise,denoise,hiss,afftdn,降噪,雜訊"),
        AudioEffectTweak.Filter("audio.fx.denoise-strong", "Noise reduction (strong)", "降噪 (強)",
            "Aggressively reduce background noise.", "大力減少背景雜訊。",
            "Reduce", "降噪", "afftdn=nr=24:nf=-30", "noise,denoise,strong,降噪,雜訊"),
        AudioEffectTweak.Filter("audio.fx.reverse", "Reverse", "倒轉播放",
            "Play the clip backwards.", "將段聲倒返轉播。",
            "Apply", "套用", "areverse", "reverse,backward,倒轉,反轉"),
        AudioEffectTweak.Filter("audio.fx.tremolo", "Tremolo", "顫音",
            "Add a wobbling amplitude tremolo.", "加抖動嘅振幅顫音。",
            "Apply", "套用", "tremolo=f=5:d=0.7", "tremolo,wobble,顫音"),
        AudioEffectTweak.Filter("audio.fx.vibrato", "Vibrato", "抖音",
            "Add a pitch vibrato.", "加音高抖動嘅抖音。",
            "Apply", "套用", "vibrato=f=6:d=0.5", "vibrato,抖音"),
        AudioEffectTweak.Filter("audio.fx.stereo-widen", "Stereo widen", "立體聲加寬",
            "Widen the stereo image.", "加闊立體聲場。",
            "Apply", "套用", "extrastereo=m=2.5", "stereo,wide,extrastereo,立體聲,加寬"),

        // ===== channel / format (5) =====
        AudioEffectTweak.Raw("audio.fx.to-mono", "Convert to mono", "轉單聲道",
            "Downmix to a single mono channel.", "混落單一單聲道。",
            "Convert", "轉換", "-i {in} -ac 1 -c:a pcm_s16le {out}", "mono,channel,單聲道,聲道"),
        AudioEffectTweak.Raw("audio.fx.to-stereo", "Convert to stereo", "轉立體聲",
            "Upmix mono to two stereo channels.", "由單聲道升做兩聲道立體聲。",
            "Convert", "轉換", "-i {in} -ac 2 -c:a pcm_s16le {out}", "stereo,channel,立體聲,聲道"),
        AudioEffectTweak.Filter("audio.fx.swap-channels", "Swap L/R channels", "左右聲道對調",
            "Swap the left and right stereo channels.", "對調左右聲道。",
            "Swap", "對調", "pan=stereo|c0=c1|c1=c0", "swap,channel,left,right,左右,聲道"),
        AudioEffectTweak.Raw("audio.fx.resample-48k", "Resample to 48 kHz", "重新取樣到 48 kHz",
            "Change the sample rate to 48000 Hz.", "將取樣率改做 48000 Hz。",
            "Apply", "套用", "-i {in} -ar 48000 -c:a pcm_s16le {out}", "resample,sample rate,48000,取樣率"),
        AudioEffectTweak.Raw("audio.fx.resample-44k", "Resample to 44.1 kHz", "重新取樣到 44.1 kHz",
            "Change the sample rate to 44100 Hz.", "將取樣率改做 44100 Hz。",
            "Apply", "套用", "-i {in} -ar 44100 -c:a pcm_s16le {out}", "resample,sample rate,44100,取樣率"),
    };
}
