using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WinForge.Services;

/// <summary>
/// .gitignore 產生器 · .gitignore generator. Embeds ~12 common .gitignore templates as static
/// strings (Node, Python, Visual Studio, VS Code, JetBrains, Rust, Java/Maven, Go, C/C++, macOS,
/// Windows, Linux) and concatenates any chosen set into one file, each under a "### <name> ###"
/// header, de-duplicating identical non-blank lines across templates. Pure managed, never throws.
/// </summary>
public static class GitignoreService
{
    /// <summary>一個範本 · One template: a stable id, a display name and its body.</summary>
    public readonly record struct Template(string Id, string Name, string Body);

    /// <summary>所有內建範本，依名排好 · All built-in templates, in display order.</summary>
    public static IReadOnlyList<Template> Templates { get; } = new[]
    {
        new Template("node", "Node", NodeBody),
        new Template("python", "Python", PythonBody),
        new Template("visualstudio", "Visual Studio", VisualStudioBody),
        new Template("vscode", "VS Code", VsCodeBody),
        new Template("jetbrains", "JetBrains", JetBrainsBody),
        new Template("rust", "Rust", RustBody),
        new Template("java", "Java / Maven", JavaBody),
        new Template("go", "Go", GoBody),
        new Template("cpp", "C / C++", CppBody),
        new Template("macos", "macOS", MacOsBody),
        new Template("windows", "Windows", WindowsBody),
        new Template("linux", "Linux", LinuxBody),
    };

    /// <summary>
    /// 合併選中嘅範本 · Concatenate the chosen templates into a single .gitignore. Each template goes
    /// under a "### <name> ###" header; identical non-blank, non-comment lines that already appeared
    /// earlier are dropped so the result has no duplicate rules. Never throws — returns "" on trouble.
    /// </summary>
    public static string Combine(IEnumerable<Template> chosen)
    {
        try
        {
            var list = (chosen ?? Enumerable.Empty<Template>()).ToList();
            if (list.Count == 0) return "";

            var seen = new HashSet<string>(StringComparer.Ordinal);
            var sb = new StringBuilder();
            sb.Append("# Generated by WinForge · WinForge 產生\n");
            sb.Append("# https://github.com — combine common .gitignore templates\n\n");

            foreach (var t in list)
            {
                sb.Append("### ").Append(t.Name).Append(" ###\n");
                var body = t.Body ?? "";
                foreach (var raw in body.Replace("\r\n", "\n").Split('\n'))
                {
                    var line = raw.TrimEnd();
                    var trimmed = line.Trim();
                    // Always keep blank lines and comments for readability; de-dup real rules only.
                    if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                    {
                        sb.Append(line).Append('\n');
                        continue;
                    }
                    if (seen.Add(trimmed))
                        sb.Append(line).Append('\n');
                }
                sb.Append('\n');
            }

            return sb.ToString().TrimEnd('\n') + "\n";
        }
        catch
        {
            return "";
        }
    }

    // ===== embedded template bodies =====

    private const string NodeBody = @"node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.pnpm-store/
.npm
.yarn/
dist/
build/
coverage/
.env
.env.local
.env.*.local
.cache/
.next/
.nuxt/
.parcel-cache/
*.tsbuildinfo";

    private const string PythonBody = @"__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
.eggs/
.installed.cfg
*.egg
.pytest_cache/
.mypy_cache/
.ruff_cache/
.coverage
htmlcov/
.tox/
.venv/
venv/
env/
ENV/
*.log";

    private const string VisualStudioBody = @"bin/
obj/
.vs/
*.user
*.suo
*.userosscache
*.sln.docstates
*.userprefs
[Dd]ebug/
[Rr]elease/
x64/
x86/
[Bb]in/
[Oo]bj/
*.pdb
*.cache
packages/
*.nupkg
TestResults/
.vsconfig";

    private const string VsCodeBody = @".vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
.history/
*.vsix";

    private const string JetBrainsBody = @".idea/
*.iml
*.ipr
*.iws
out/
.idea_modules/
atlassian-ide-plugin.xml
cmake-build-*/
*.iws";

    private const string RustBody = @"/target/
**/*.rs.bk
Cargo.lock
*.pdb";

    private const string JavaBody = @"target/
*.class
*.jar
*.war
*.ear
*.nar
hs_err_pid*
replay_pid*
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar
build/
.gradle/";

    private const string GoBody = @"*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
go.work
go.work.sum
vendor/
bin/";

    private const string CppBody = @"*.o
*.obj
*.a
*.lib
*.so
*.dylib
*.dll
*.exe
*.out
*.app
*.gch
*.pch
build/
cmake-build-*/
CMakeFiles/
CMakeCache.txt";

    private const string MacOsBody = @".DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes
.fseventsd
.DocumentRevisions-V100
.TemporaryItems
.apdisk";

    private const string WindowsBody = @"Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
Desktop.ini
$RECYCLE.BIN/
*.stackdump
*.cab
*.msi
*.msix
*.lnk";

    private const string LinuxBody = @"*~
.fuse_hidden*
.directory
.Trash-*
.nfs*
.cache/";
}
