using System.Collections.Generic;
using System.Linq;

namespace WinForge.Services;

/// <summary>一個應用程式內模組（頁面）· One in-app module (page) for page-search.</summary>
public sealed class ModuleInfo
{
    public string Tag { get; init; } = "";
    public string En { get; init; } = "";
    public string Zh { get; init; } = "";
    public string Glyph { get; init; } = "";
    public string Keywords { get; init; } = "";

    public string Haystack => $"{En} {Zh} {Keywords}".ToLowerInvariant();
}

/// <summary>
/// 所有模組頁面嘅登記（畀搜尋用）· Registry of every module page, used by the master/page search.
/// </summary>
public static class ModuleRegistry
{
    public static readonly List<ModuleInfo> All = new()
    {
        new() { Tag = "dashboard", En = "Dashboard", Zh = "概覽", Glyph = "", Keywords = "home overview start 主頁 概覽" },
        new() { Tag = "module.vscode", En = "VS Code", Zh = "VS Code 編輯器", Glyph = ((char)0xE943).ToString(), Keywords = "vscode vs code visual studio code editor cli open file folder workspace new window reuse diff merge goto line extension install uninstall list profile insiders tunnel remote settings keybindings code-workspace 編輯器 擴充功能 比對 合併 設定 遠端 隧道" },
        new() { Tag = "module.git", En = "Git & GitHub", Zh = "Git 與 GitHub", Glyph = "", Keywords = "git github commit push pull fetch repo repos list clone branch tag merge rebase stash remote worktree submodule uploader issue pull request pr actions workflow release gist secret label star fork notifications gh cli gitty up checkpoint restore alias undo share workflow 版本控制 儲存庫 分支 標籤 工作流程 別名 撤回 檢查點" },
        new() { Tag = "module.peek", En = "Peek", Zh = "快速預覽", Glyph = ((char)0xE7B3).ToString(), Keywords = "peek preview quick look quicklook file viewer image text code markdown pdf audio video archive metadata previewer prev next folder navigate hotkey 快速預覽 預覽 檔案 圖片 文字 程式碼 影片 音訊 壓縮檔 中繼資料 熱鍵 上一個 下一個" },
        new() { Tag = "module.archives", En = "Archives", Zh = "壓縮檔", Glyph = "", Keywords = "zip 7z rar tar gzip compress extract 解壓 壓縮" },
        new() { Tag = "module.media", En = "Media", Zh = "媒體", Glyph = "", Keywords = "ffmpeg video audio convert trim gif 影片 音訊 轉檔" },
        new() { Tag = "module.audioeditor", En = "Audio Editor", Zh = "音訊編輯器", Glyph = ((char)0xE8D6).ToString(), Keywords = "audio editor audacity waveform record mic microphone play playback trim fade normalize gain volume speed tempo pitch shift noise reduction denoise reverb echo compressor eq equalizer mix concat export wav mp3 flac 音訊 編輯 波形 錄音 播放 剪裁 淡入 淡出 正規化 增益 變速 變調 降噪 混音 匯出" },
        new() { Tag = "module.mediaplayer", En = "Media Player", Zh = "媒體播放器", Glyph = ((char)0xE714).ToString(), Keywords = "vlc libvlc media player play video audio movie music stream url playlist subtitle audio track snapshot fullscreen seek volume transcode convert mp4 mp3 webm wav 播放器 媒體 影片 音樂 串流 播放清單 字幕 截圖 全螢幕 轉檔" },
        new() { Tag = "module.ytdlp", En = "Media Downloader", Zh = "媒體下載器", Glyph = ((char)0xE896).ToString(), Keywords = "yt-dlp ytdlp youtube download downloader video audio mp3 m4a playlist subtitles subs format quality 1080p 720p thumbnail metadata sponsorblock cookies twitch vimeo soundcloud bilibili 下載 影片 音訊 字幕 播放清單 畫質 縮圖" },
        new() { Tag = "module.blender", En = "Blender (3D / Render)", Zh = "Blender（3D／算圖）", Glyph = ((char)0xE7F4).ToString(), Keywords = "blender 3d render rendering cycles eevee headless animation frame gltf fbx obj python script batch queue cpu gpu samples output 算圖 渲染 動畫 影格 匯出 批次 佇列" },
        new() { Tag = "module.libreoffice", En = "Document Converter", Zh = "文件轉換器", Glyph = ((char)0xE8A5).ToString(), Keywords = "libreoffice soffice document converter convert batch pdf docx xlsx odt ods pptx csv txt office writer calc impress headless 文件 轉換 轉檔 批次 辦公" },
        new() { Tag = "module.regedit", En = "Registry Editor", Zh = "登錄編輯器", Glyph = "", Keywords = "registry regedit hive key value 登錄檔" },
        new() { Tag = "module.doctors", En = "System Doctors", Zh = "系統醫生", Glyph = ((char)0xE95E).ToString(), Keywords = "doctor repair fix rescue printer spooler dns network sleep wake taskbar start search index explorer icon thumbnail cache ownership permissions 修復 醫生 救援 列印 網絡 睡眠 喚醒 工作列 搜尋 圖示 縮圖 擁有權 權限" },
        new() { Tag = "module.services", En = "Services", Zh = "服務", Glyph = "", Keywords = "services start stop startup type 服務" },
        new() { Tag = "module.tasks", En = "Scheduled Tasks", Zh = "排程工作", Glyph = "", Keywords = "scheduled task scheduler run 排程" },
        new() { Tag = "module.devices", En = "Devices", Zh = "裝置", Glyph = "", Keywords = "device manager hardware driver 裝置 驅動" },
        new() { Tag = "module.vivetool", En = "ViVeTool", Zh = "功能旗標", Glyph = ((char)0xE9D5).ToString(), Keywords = "vivetool vive feature flag experiment hidden file explorer tabs new start menu modern context menu snap layouts energy saver click to do 功能 旗標 實驗 隱藏 分頁 開始功能表" },
        new() { Tag = "module.startup", En = "Startup Apps", Zh = "開機程式", Glyph = "", Keywords = "startup autostart logon run 開機 自啟動" },
        new() { Tag = "module.rename", En = "Batch Rename", Zh = "批次改名", Glyph = "", Keywords = "rename bulk powerrename regex 改名 批次" },
        new() { Tag = "module.bulkops", En = "Bulk File Ops", Zh = "批次檔案操作", Glyph = "", Keywords = "bulk file move copy delete attributes 批次 檔案" },
        new() { Tag = "module.newplus", En = "New+", Zh = "範本新增", Glyph = ((char)0xE710).ToString(), Keywords = "new plus newplus powertoys template templates create file folder new menu shellnew context menu date variable substitution scaffold blank boilerplate 範本 新增 範本新增 建立 檔案 資料夾 新增選單 變數 日期 樣板 鷹架" },
        new() { Tag = "module.duplicates", En = "Duplicate Finder", Zh = "重複檔案搜尋", Glyph = "", Keywords = "duplicate hash find dedupe 重複" },
        new() { Tag = "module.filelocksmith", En = "File Locksmith", Zh = "檔案鎖偵測", Glyph = ((char)0xE72E).ToString(), Keywords = "file locksmith locked file folder which process is locking handle open handle restart manager rstrtmgr in use cannot delete cannot move being used by another program end task unlock who is using whatslocking lockedfile powertoys 檔案鎖 鎖住 邊個程序 鎖定 控制代碼 佔用 刪唔到 移動唔到 解鎖 結束工作 開啟中" },
        new() { Tag = "module.disk", En = "Disk Analyser", Zh = "磁碟分析", Glyph = "", Keywords = "disk space treemap analyse folder size 磁碟 空間" },
        new() { Tag = "module.drives", En = "Drives", Zh = "磁碟機", Glyph = "", Keywords = "drive volume format bitlocker 磁碟機" },
        new() { Tag = "module.testdisk", En = "TestDisk / PhotoRec Recovery", Zh = "TestDisk / PhotoRec 資料救援", Glyph = ((char)0xE7BA).ToString(), Keywords = "testdisk photorec recovery carve undelete partition recover data lost deleted 資料救援 救援 復原 還原 分割區 救回 刪除 檔案" },
        new() { Tag = "module.uninstall", En = "App Uninstaller", Zh = "應用程式解除安裝", Glyph = "", Keywords = "uninstall remove app program winget 解除安裝" },
        new() { Tag = "module.windows", En = "Window Manager", Zh = "視窗管理", Glyph = "", Keywords = "window tile cascade always on top 視窗" },
        new() { Tag = "module.workspaces", En = "Workspaces", Zh = "工作區", Glyph = ((char)0xE7C4).ToString(), Keywords = "workspaces workspace powertoys app layout desktop layout capture snapshot restore relaunch launch window position size monitor maximized minimized set of apps project save named scene session arrange reopen 工作區 應用程式佈局 桌面佈局 擷取 快照 還原 重新啟動 啟動 視窗位置 大細 螢幕 場景 工作階段 一組應用程式 儲存 重開" },
        new() { Tag = "module.altsnap", En = "AltSnap", Zh = "Alt 拖曳視窗", Glyph = ((char)0xE7C4).ToString(), Keywords = "altsnap alt drag move resize window modifier key altdrag snap aero hook ramonunch alt 拖曳 移動 縮放 修飾鍵 貼齊 視窗" },
        new() { Tag = "module.fancyzones", En = "FancyZones", Zh = "視窗分區", Glyph = ((char)0xE80A).ToString(), Keywords = "fancyzones fancy zones powertoys window tiling zone editor layout grid columns rows priority snap hotkey shift drag win ctrl arrow tile 分區 排版 貼齊 版面 格網 編輯器 熱鍵" },
        new() { Tag = "module.komorebi", En = "Komorebi (Tiling WM)", Zh = "Komorebi 平鋪視窗管理", Glyph = ((char)0xE80A).ToString(), Keywords = "komorebi komorebic tiling window manager tile bsp columns rows stack grid monocle float workspace monitor layout daemon wm whkd gaps padding 平鋪 視窗管理 排版 工作區 守護程序 間距" },
        new() { Tag = "module.glazewm", En = "GlazeWM Tiling", Zh = "GlazeWM 平鋪視窗", Glyph = ((char)0xE737).ToString(), Keywords = "glazewm glaze tiling window manager tile workspace keybinding gaps config yaml komorebi reload daemon 平鋪 視窗 管理 工作區 鍵盤 綁定 邊距 設定" },
        new() { Tag = "module.keyboard", En = "Keyboard Remapper", Zh = "鍵盤重新對應", Glyph = "", Keywords = "keyboard remap key sharpkeys 鍵盤" },
        new() { Tag = "module.hotkeys", En = "Hotkey & Macro Runner", Zh = "熱鍵與巨集", Glyph = ((char)0xE765).ToString(), Keywords = "hotkey macro shortcut chord registerhotkey send keys autohotkey text expander snippet trigger expand abbreviation 熱鍵 巨集 快捷鍵 文字展開 片語 縮寫" },
        new() { Tag = "module.shortcutguide", En = "Shortcut Guide", Zh = "快捷鍵指南", Glyph = ((char)0xE765).ToString(), Keywords = "shortcut guide powertoys windows key win hold overlay cheat sheet keyboard shortcuts reference table win+e win+d win+l win+tab snap emoji clipboard snip search hotkey list winkey 快捷鍵 指南 揿住 視窗鍵 覆蓋層 鍵盤 速查表 參考 貼齊 表情符號 剪貼簿" },
        new() { Tag = "module.cmdpalette", En = "Command Palette", Zh = "指令面板", Glyph = ((char)0xE773).ToString(), Keywords = "command palette powertoys run launcher quick launch alt space search box global hotkey app launcher calculator run command open url system action lock sleep shutdown restart web search fuzzy spotlight wox flow 指令面板 快速啟動 啟動器 搜尋框 全域熱鍵 計算機 執行 開網址 系統動作 鎖定 睡眠 關機 重啟 網絡搜尋 模糊搜尋" },
        new() { Tag = "module.hosts", En = "Hosts Editor", Zh = "hosts 編輯器", Glyph = "", Keywords = "hosts block domain dns 封鎖" },
        new() { Tag = "module.mouse", En = "Mouse & Pointer", Zh = "滑鼠與指標", Glyph = "", Keywords = "mouse pointer acceleration speed 滑鼠 指標" },
        new() { Tag = "module.mwb", En = "Mouse Without Borders", Zh = "無界滑鼠", Glyph = ((char)0xE962).ToString(), Keywords = "mouse without borders mwb kvm share keyboard mouse multiple pc computers lan network control switch machine clipboard sync pair pairing security key tcp aes encrypt edge transition layout synergy barrier software kvm 無界滑鼠 鍵鼠共享 共享 鍵盤 滑鼠 多部電腦 區域網 配對 安全密鑰 剪貼簿 同步 邊界 控制權 版面" },
        new() { Tag = "module.recorder", En = "Screen Recorder", Zh = "螢幕錄影", Glyph = "", Keywords = "record screen capture gdigrab 錄影" },
        new() { Tag = "module.capture", En = "Capture Studio", Zh = "擷取工作室", Glyph = ((char)0xE722).ToString(), Keywords = "capture snip screenshot region gif ocr text recognize clipboard 截圖 擷取 區域 文字辨識 認字" },
        new() { Tag = "module.cropandlock", En = "Crop And Lock", Zh = "裁切與鎖定", Glyph = ((char)0xE7A8).ToString(), Keywords = "crop and lock croplock cropandlock window crop thumbnail reparent always on top topmost dwm thumbnail live mirror region pin floating powertoys windowcrop 裁切 鎖定 視窗 縮圖 置頂 浮窗 即時 鏡像 範圍 釘選" },
        new() { Tag = "module.giflab", En = "GIF Studio", Zh = "螢幕轉 GIF", Glyph = ((char)0xE786).ToString(), Keywords = "gif studio screentogif screen to gif record region window fullscreen frames frame editor delete reorder crop export mp4 apng palette animation 螢幕轉 動畫 畫面格 刪格 調次序 裁切 匯出 錄影 區域 視窗 全螢幕" },
        new() { Tag = "module.zoomit", En = "ZoomIt", Zh = "螢幕放大與標註", Glyph = ((char)0xE71E).ToString(), Keywords = "zoomit zoom magnify magnifier screen presentation annotate annotation draw pen freehand arrow rectangle highlighter marker break timer countdown sysinternals hotkey ctrl 1 2 3 colour color red green blue orange yellow thickness pan wheel esc 放大 放大鏡 標註 註解 畫筆 手畫 箭咀 矩形 螢光筆 小休 倒數 計時 簡報 演示 熱鍵 顏色 平移 滾輪" },
        new() { Tag = "module.winfetch", En = "System Info (Winfetch)", Zh = "系統資訊", Glyph = ((char)0xE7F4).ToString(), Keywords = "winfetch neofetch fetch system info os host kernel uptime packages shell resolution gpu cpu memory disk ascii logo specs about machine 系統資訊 規格 開機時間 解像度 記憶體 磁碟 顯示卡 標誌" },
        new() { Tag = "module.monitor", En = "System Monitor", Zh = "系統監察", Glyph = "", Keywords = "cpu ram memory network task manager priority affinity btop btop4win resource monitor per-core swap sparkline efficiency 監察 工作管理員 資源監控 每核心" },
        new() { Tag = "module.battery", En = "Battery & Thermal", Zh = "電池與散熱", Glyph = ((char)0xE83E).ToString(), Keywords = "battery thermal temperature wear health cpu gpu fan powercfg batteryreport energy 電池 溫度 散熱 風扇 耗損 健康" },
        new() { Tag = "module.connections", En = "Connections", Zh = "連線", Glyph = "", Keywords = "tcp udp connections netstat tcpview port 連線" },
        new() { Tag = "module.wireshark", En = "Packet Capture", Zh = "封包擷取", Glyph = ((char)0xEDA3).ToString(), Keywords = "wireshark packet capture tshark dumpcap pcap pcapng sniff npcap interface bpf capture filter display filter protocol tcp udp http dns follow stream conversation endpoint statistics 封包 擷取 抓包 嗅探 過濾 協定 統計" },
        new() { Tag = "module.nmap", En = "Nmap Scanner", Zh = "網絡掃描", Glyph = ((char)0xE9D2).ToString(), Keywords = "nmap port scan network security host service os version cidr subnet npcap zenmap nse script ping sweep 掃描 端口 連接埠 網絡 安全 主機 服務 作業系統 子網" },
        new() { Tag = "module.events", En = "Event Viewer", Zh = "事件檢視器", Glyph = "", Keywords = "event log viewer system application 事件 記錄" },
        new() { Tag = "module.mixer", En = "Volume Mixer", Zh = "音量混合器", Glyph = "", Keywords = "volume mixer audio per-app mute 音量 靜音" },
        new() { Tag = "module.contextmenu", En = "Context Menu", Zh = "右鍵選單", Glyph = "", Keywords = "context menu right click verb 右鍵 選單" },
        new() { Tag = "module.taskbar-tweaker", En = "Taskbar Tweaker", Zh = "工作列調校", Glyph = ((char)0xE71D).ToString(), Keywords = "taskbar tweaker 7+ taskbar tweaker windhawk align combine buttons small icons tray system tray multi monitor seconds clock search task view widgets copilot end task start menu explorer 工作列 調校 對齊 合併 系統匣 多螢幕 秒 時鐘 搜尋 開始功能表 結束工作" },
        new() { Tag = "module.lightswitch", En = "LightSwitch (Auto Dark Mode)", Zh = "自動深淺色", Glyph = ((char)0xE793).ToString(), Keywords = "lightswitch light switch auto dark mode autotheme darkmode automatic theme schedule sunrise sunset day night fixed time apps system personalize appsuselighttheme systemuseslighttheme latitude longitude location ip geolocation background scheduled task switch now powertoys 自動 深淺色 深色模式 淺色模式 主題 切換 排程 日出 日落 日夜 固定時間 緯度 經度 位置 背景 排程工作" },
        new() { Tag = "module.nilesoftshell", En = "Nilesoft Shell", Zh = "Nilesoft 右鍵選單", Glyph = ((char)0xE7BA).ToString(), Keywords = "nilesoft shell context menu nss shell.nss register unregister reload theme modern dark snippet template explorer customize right click 右鍵 選單 主題 註冊 設定 範本 片語 客製化" },
        new() { Tag = "module.awake", En = "Awake", Zh = "保持喚醒", Glyph = "", Keywords = "awake keep awake no sleep caffeine 唔瞓 喚醒" },
        new() { Tag = "module.colorpicker", En = "Color Picker", Zh = "螢幕取色", Glyph = "", Keywords = "color picker hex rgb hsl eyedropper 取色 顏色" },
        new() { Tag = "module.screenruler", En = "Screen Ruler", Zh = "螢幕間尺", Glyph = ((char)0xE1A6).ToString(), Keywords = "screen ruler measure tool measurement powertoys distance horizontal vertical cross crosshair bounds pixel px coordinate angle line color thickness overlay clipboard 間尺 度尺 量度 量尺 螢幕度尺 像素 距離 水平 垂直 十字 邊界 座標 角度 覆蓋層" },
        new() { Tag = "module.pixeleditor", En = "Pixel Editor", Zh = "像素畫編輯器", Glyph = ((char)0xE790).ToString(), Keywords = "pixel editor aseprite sprite pixel art draw paint canvas palette layers frames animation gif png pencil eraser fill bucket eyedropper undo redo 像素 像素畫 精靈 繪圖 畫布 調色盤 圖層 影格 動畫 鉛筆 橡皮 填色 吸色" },
        new() { Tag = "module.envvars", En = "Environment Variables", Zh = "環境變數", Glyph = "", Keywords = "environment variables path user system env 環境變數" },
        new() { Tag = "module.clipboard", En = "Clipboard", Zh = "剪貼簿", Glyph = ((char)0xE77F).ToString(), Keywords = "clipboard history text image file convert win+v qr qrcode qr code plain text paste 剪貼簿 歷史 二維碼 純文字" },
        new() { Tag = "module.advancedpaste", En = "Advanced Paste", Zh = "進階貼上", Glyph = ((char)0xE77F).ToString(), Keywords = "advanced paste transform smart paste plain text markdown json uppercase lowercase title case base64 url encode html ocr image to text csv transpose sort unique lines ai win+shift+v 進階 貼上 轉換 純文字 大小寫 編碼 解碼 排序 去重複 圖片轉文字" },
        new() { Tag = "module.packages", En = "Package Manager", Zh = "套件管理", Glyph = ((char)0xECAA).ToString(), Keywords = "winget package install uninstall upgrade update scoop choco chocolatey pip python npm node dotnet tool powershell gallery psgallery pwsh pwsh7 psresource cargo rust bun javascript vcpkg dependencies unigetui discover bundle export import batch select selected multi 套件 安裝 更新 解除安裝 相依 清單 批次 多選 匯出 匯入" },
        new() { Tag = "module.adb", En = "Android (ADB)", Zh = "Android（ADB）", Glyph = ((char)0xE8EA).ToString(), Keywords = "android adb apk logcat shell screenshot reboot fastboot scrcpy push pull file backup mirror 手機 安卓 鏡像 備份" },
        new() { Tag = "module.fastboot", En = "Fastboot / Flasher", Zh = "Fastboot／刷機", Glyph = ((char)0xE7BA).ToString(), Keywords = "fastboot flash flasher bootloader unlock boot.img factory image sideload ota pixelflasher 刷機 解鎖" },
        new() { Tag = "module.emulator", En = "Android Emulator & SDK", Zh = "Android 模擬器與 SDK", Glyph = ((char)0xE8EA).ToString(), Keywords = "android emulator avd avdmanager sdkmanager virtual device launch wipe cold boot sdk sdkmanager packages platform-tools build-tools ndk license channel system image install uninstall update 套件 平台 授權 模擬器 虛擬裝置 安裝 更新 移除" },
        new() { Tag = "module.vpn", En = "VPN & Mesh", Zh = "VPN 與網狀網", Glyph = ((char)0xE945).ToString(), Keywords = "vpn nordvpn tailscale mesh connect exit node ping 連線 網狀網" },
        new() { Tag = "module.rustdesk", En = "RustDesk", Zh = "遠端桌面", Glyph = ((char)0xE8AF).ToString(), Keywords = "rustdesk remote desktop remote control id password peer connect relay server self-hosted unattended access teamviewer anydesk alternative 遠端桌面 遙距桌面 遠程桌面 遠端控制 遙距控制" },
        new() { Tag = "module.homeassistant", En = "Home Assistant", Zh = "家居助理", Glyph = ((char)0xE80F).ToString(), Keywords = "home assistant ha smart home rest api template scene script light climate thermostat camera notify intent calendar 智能家居 家居助理" },
        new() { Tag = "module.qbittorrent", En = "qBittorrent", Zh = "種子下載", Glyph = ((char)0xE896).ToString(), Keywords = "qbittorrent torrent torrents magnet bittorrent download seed leech tracker peer category tag webui web api speed limit 種子 磁力 下載 做種 追蹤器 分類 標籤 速度限制" },
        new() { Tag = "module.torrent", En = "Native Torrent", Zh = "原生種子下載", Glyph = ((char)0xE118).ToString(), Keywords = "native torrent bittorrent monotorrent magnet link dht pex local peer discovery udp http tracker in-process managed pure c# download seed leech file priority sequential recheck ratio eta peers seeds pieces fast resume session restore downloads 原生 種子 磁力 下載 做種 追蹤器 對等 內建 受控 引擎 檔案優先 順序 重新檢查 比率 片段 還原" },
        new() { Tag = "module.comms", En = "Communications", Zh = "通訊", Glyph = ((char)0xE8BD).ToString(), Keywords = "communications mail email outlook mailto draft attach teams meeting call discord telegram slack phone link tel sms deep link 通訊 信件 電郵 草稿 會議 電話" },
        new() { Tag = "module.configbackup", En = "Config & Backup", Zh = "設定與備份", Glyph = ((char)0xE8F7).ToString(), Keywords = "config backup snapshot restore export import bundle zip git schedule mirror reg winget integrity secrets ssh api key encrypt aes password 設定 備份 快照 還原 匯出 匯入 排程 鏡像 加密 密鑰 機密" },
        new() { Tag = "module.worldmonitor", En = "World Monitor", Zh = "世界監察", Glyph = ((char)0xE909).ToString(), Keywords = "world monitor worldmonitor news geopolitics finance commodity energy happy instability index intelligence dashboard globe map webview variant 世界 監察 新聞 地緣政治 金融 商品 能源 情報 儀表板 地球 不穩定指數" },
        new() { Tag = "module.native", En = "Native Utilities", Zh = "原生工具", Glyph = ((char)0xE950).ToString(), Keywords = "wifi password saved nearby scan smb shares sessions brightness ddc certificate users logoff disconnect gpu disk counters process modules bluetooth pinvoke wlan 原生 密碼 共享 亮度 憑證 藍牙 模組" },
        new() { Tag = "module.powertoys", En = "PowerToys Extras", Zh = "PowerToys 額外工具", Glyph = ((char)0xE945).ToString(), Keywords = "powertoys image resizer ocr text extractor always on top topmost paste plain text 圖片縮放 文字擷取 置頂 純文字" },
        new() { Tag = "module.wslvm", En = "WSL & VM Launcher", Zh = "WSL 與 VM 啟動器", Glyph = ((char)0xEC7A).ToString(), Keywords = "wsl linux distro ubuntu debian windows sandbox wsb virtual machine vm hyper-v export import 子系統 沙盒 虛擬機" },
        new() { Tag = "module.virtualbox", En = "VirtualBox Manager", Zh = "VirtualBox 管理", Glyph = ((char)0xEC7A).ToString(), Keywords = "virtualbox vbox vboxmanage vm virtual machine snapshot clone ova headless oracle 虛擬機 虛擬機器 快照 複製 匯入 匯出" },
        new() { Tag = "module.terminal", En = "Windows Terminal", Zh = "Windows 終端機", Glyph = ((char)0xE756).ToString(), Keywords = "windows terminal wt settings.json profiles profile editor conpty pseudo console embedded shell pwsh powershell cmd wsl color scheme font default duplicate launch new tab pane 終端機 設定檔 內嵌 偽終端機 殼層 預設 複製 啟動 分頁 窗格 色彩配置 字型" },
        new() { Tag = "module.fonts", En = "Font Manager", Zh = "字型管理", Glyph = ((char)0xE8D2).ToString(), Keywords = "font fonts install preview uninstall ttf otf typeface typography 字型 字款 安裝 預覽 移除" },
        new() { Tag = "module.onedrive", En = "OneDrive", Zh = "OneDrive", Glyph = ((char)0xE753).ToString(), Keywords = "onedrive files on demand pin dehydrate online only cloud free space storage sense sync 雲端 釘選 脫水 釋放空間 同步 隨選" },
        new() { Tag = "module.richpreview", En = "Rich Preview", Zh = "豐富預覽", Glyph = ((char)0xE8A1).ToString(), Keywords = "rich preview preview pane peek file explorer add-ons handlers svg markdown md pdf source code json xml yaml toml gcode g-code 3d print qoi image thumbnail metadata render viewer webview2 monaco powertoys file preview drop open prev next 預覽 預覽窗格 檔案 渲染 縮圖 圖片 原始碼 開發 拖放" },
        new() { Tag = "module.timeunit", En = "Time & Unit Tools", Zh = "時間與單位工具", Glyph = ((char)0xE823).ToString(), Keywords = "time zone timezone world clock converter convert unit length mass temperature 時間 時區 世界時鐘 換算 單位" },
        new() { Tag = "module.settingshub", En = "Settings & Control Panel", Zh = "設定與控制台", Glyph = ((char)0xE713).ToString(), Keywords = "settings control panel ms-settings applet cpl launcher open page 設定 控制台 啟動器 面板" },
        new() { Tag = "module.amulet", En = "Minecraft World Editor (Amulet)", Zh = "Minecraft 世界編輯器（Amulet）", Glyph = ((char)0xE7FC).ToString(), Keywords = "amulet minecraft world editor map editor java bedrock level dat nbt python wxpython launch backup saves chunk dimension 世界 編輯器 我的世界 地圖 備份 存檔 維度" },
        new() { Tag = "module.minecraftserver", En = "Minecraft Server", Zh = "Minecraft 伺服器", Glyph = ((char)0xE7FC).ToString(), Keywords = "minecraft server paper spigot papermc buildtools eula server.properties plugin plugins luckperms essentialsx viaversion worldedit console rcon start.bat aikar gradle maven jar 伺服器 外掛 主控台 我的世界" },
        new() { Tag = "module.imaging", En = "Imaging & Game Tools", Zh = "燒錄與遊戲工具", Glyph = ((char)0xE7F4).ToString(), Keywords = "raspberry pi imager sd card flash image write boot ssh wifi minecraft world downloader proxy jar rufus usb bootable iso flash drive uefi mbr verify windows linux installer 開機 USB 手指 啟動碟 樹莓派 燒錄 映像 我的世界 下載" },
        new() { Tag = "module.voice", En = "Voice & Read-Aloud", Zh = "語音朗讀", Glyph = ((char)0xE767).ToString(), Keywords = "voice tts text to speech read aloud speak narrator wav export sapi 語音 朗讀 文字轉語音 讀出" },
        new() { Tag = "module.viaproxy", En = "ViaProxy", Zh = "Minecraft 版本代理", Glyph = ((char)0xE990).ToString(), Keywords = "viaproxy minecraft version proxy viaversion viabackwards viarewind protocol translate bridge server jar java cli bind target auth offline online mc 我的世界 版本 代理 協定 轉換 伺服器" },
        new() { Tag = "module.aiagents", En = "AI Agents", Zh = "AI 代理", Glyph = ((char)0xE99A).ToString(), Keywords = "ai agent claude code codex opencode pi openclaw hermes coding agent terminal cli install launch api key 代理 編程 安裝 啟動" },
        new() { Tag = "module.resume", En = "Resume Writer", Zh = "履歷與求職信寫手", Glyph = ((char)0xE8A5).ToString(), Keywords = "resume cv cover letter job application tailor ai writer generate export base history docx pdf markdown 履歷 求職信 應徵 工作 職位 自我推薦 度身 生成 匯出" },
        new() { Tag = "module.aichat", En = "AI Chat", Zh = "AI 聊天", Glyph = ((char)0xE8BD).ToString(), Keywords = "ai chat llm ollama openai openrouter lm studio llama.cpp gpt local model conversation prompt streaming system prompt temperature openwebui open webui markdown 聊天 對話 本機模型 提示 串流 系統提示 溫度" },
        new() { Tag = "module.cloudflare", En = "Cloudflare & Tunnel", Zh = "Cloudflare 與 Tunnel", Glyph = ((char)0xE753).ToString(), Keywords = "cloudflare cloudflared tunnel quick tunnel trycloudflare access warp dns over https doh zero trust route ingress 隧道 加密 連線" },
        new() { Tag = "module.weblogin", En = "In-App Login", Zh = "內置登入", Glyph = ((char)0xE77B).ToString(), Keywords = "login sign in signin oauth webview2 web view browser embedded auth authentication token cookie session redirect callback github cloudflare openai anthropic bitwarden account credentials 登入 登錄 內置 瀏覽器 認證 帳戶 憑證 權杖 重新導向" },
        new() { Tag = "module.ssh", En = "SSH Toolset", Zh = "SSH 工具", Glyph = ((char)0xE756).ToString(), Keywords = "ssh sftp scp terminal shell remote profile key keygen ed25519 rsa passwordless deploy authorized_keys known hosts openssh dpapi 終端機 遠端 金鑰 免密碼 部署 連線 上載 下載" },
        new() { Tag = "module.vault-volumes", En = "WinForge Vault", Zh = "WinForge 保險庫", Glyph = ((char)0xE72E).ToString(), Keywords = "vault volume container encrypt encrypted disk encryption mount dismount unmount drive letter password keyfile pim benchmark aes serpent twofish on the fly cryptography 保險庫 加密 容器 磁碟 掛載 卸載 密碼 鎖匙檔 磁碟區" },
        new() { Tag = "module.mail", En = "Mail", Zh = "電郵", Glyph = ((char)0xE715).ToString(), Keywords = "mail email imap smtp thunderbird inbox compose reply forward attachment oauth gmail outlook icloud yahoo account folder message read send 電郵 郵件 收件匣 撰寫 回覆 轉寄 附件 帳戶 資料夾 訊息" },
        new() { Tag = "module.packer", En = "Packer (Image Builder)", Zh = "Packer（映像建置器）", Glyph = ((char)0xE7B8).ToString(), Keywords = "packer hashicorp image builder template hcl pkr.hcl json init validate fmt format build inspect plugin plugins var var-file variables provisioner builder source qemu docker aws azure vsphere amazon ami vm machine devops 映像 範本 建置 變數 插件" },
        new() { Tag = "module.webcloner", En = "Website Cloner", Zh = "網站複製器", Glyph = ((char)0xE774).ToString(), Keywords = "website cloner clone copy site web page scrape download fetch assets html css js mirror rebuild reverse engineer ai agent webview2 design tokens 網站 複製 抓取 下載 鏡像 重建 設計符記" },
        new() { Tag = "module.windhawk", En = "Windhawk Mods", Zh = "Windhawk 模組", Glyph = ((char)0xE945).ToString(), Keywords = "windhawk mod mods customize taskbar height icon size clock start menu styler explorer rounded corners classic taskbar aero tray injection ramensoftware 模組 自訂 工作列 時鐘 開始功能表 圓角 注入" },
        new() { Tag = "module.rainmeter", En = "Rainmeter Widgets", Zh = "Rainmeter 桌面小工具", Glyph = ((char)0xE7F4).ToString(), Keywords = "rainmeter skin skins widget widgets desktop gadget bang activate deactivate toggle refresh hide show rmskin skininstaller layout illustro clock cpu monitor personalization 桌面 小工具 皮膚 桌面美化 個人化 時鐘 監察" },
        new() { Tag = "module.pgadmin", En = "Postgres Tool", Zh = "Postgres 工具 / pgAdmin", Glyph = ((char)0xE94D).ToString(), Keywords = "postgres postgresql pgadmin sql database query npgsql connection schema table view server psql 資料庫 數據庫 查詢 表 檢視 結構描述 連線" },
        new() { Tag = "module.filezilla", En = "FTP / SFTP", Zh = "FTP／SFTP 檔案傳輸", Glyph = ((char)0xE8B7).ToString(), Keywords = "ftp sftp ftps filezilla file transfer client site manager upload download dual pane transfer queue resume tls ssh private key dpapi 檔案傳輸 上載 下載 站台 佇列 續傳 私鑰" },
        new() { Tag = "module.ollama", En = "Ollama", Zh = "本地大模型", Glyph = ((char)0xE99A).ToString(), Keywords = "ollama llm local ai model chat gguf llama mistral qwen gemma phi deepseek pull serve tags running ps temperature top_p num_ctx streaming 本地 模型 聊天 人工智能 下載 大模型" },
        new() { Tag = "module.bitwarden", En = "Bitwarden Vault", Zh = "Bitwarden 密碼庫", Glyph = ((char)0xE72E).ToString(), Keywords = "bitwarden bw vault password manager login unlock master password totp 2fa two factor generate generator passphrase secret sync clipboard self-hosted vaultwarden 密碼庫 密碼 管理 解鎖 主密碼 驗證碼 產生 同步 機密" },
        new() { Tag = "module.timelens", En = "Activity Timeline", Zh = "活動時間軸", Glyph = ((char)0xE81C).ToString(), Keywords = "timelens activity timeline time tracking tracker foreground window app usage productivity insights idle per-app totals stacked bar export csv 活動 時間軸 時間追蹤 前景 視窗 應用程式 使用量 生產力 閒置 匯出" },
        new() { Tag = "module.quicktype", En = "quicktype", Zh = "JSON 轉型別", Glyph = ((char)0xE943).ToString(), Keywords = "quicktype json schema typescript graphql postman code generator type csharp c# python go rust java kotlin swift objective-c c++ dart ruby elm php scala types just-types namespace newtonsoft system.text.json npm node jsontotype codegen 程式碼產生 型別 產生 轉換 結構" },
        new() { Tag = "module.aws", En = "AWS CLI", Zh = "AWS 命令列", Glyph = ((char)0xE753).ToString(), Keywords = "aws amazon web services cli s3 ec2 iam lambda cloudwatch logs sts profile credentials region sso configure bucket instance describe generic command browser skeleton dynamodb sns sqs ssm cloudformation route53 rds 雲端 命令列 設定檔 憑證 區域 儲存桶 執行個體" },
        new() { Tag = "module.mouseutils", En = "Mouse Utilities", Zh = "滑鼠工具", Glyph = ((char)0xE7C1).ToString(), Keywords = "mouse utilities utils powertoys find my mouse findmymouse spotlight sonar double ctrl shake highlighter highlight click circle crosshairs crosshair lines pointer jump teleport screenshot overlay hook cursor locate ring 滑鼠 工具 搵滑鼠 聚光燈 標示 點擊 十字線 指標 跳轉 傳送 截圖 覆蓋層 游標 光圈" },
        new() { Tag = "module.quickaccent", En = "Quick Accent", Zh = "快速重音符", Glyph = ((char)0xE8D3).ToString(), Keywords = "quick accent accents diacritic diacritics mark marks acute grave circumflex tilde umlaut macron breve caron cedilla ring special symbols currency ipa pinyin powertoys keyboard hook hold letter activation key space arrow popup variants insert sendinput unicode language french german spanish portuguese vietnamese 快速 重音 重音符 變音 標記 發音符號 特殊符號 貨幣 拼音 音標 鍵盤 鈎 候選 語言 法文 德文 西班牙文 葡萄牙文 越南文" },
        new() { Tag = "module.cmdnotfound", En = "Command Not Found", Zh = "搵唔到指令", Glyph = ((char)0xE756).ToString(), Keywords = "command not found cmdnotfound commandnotfound winget suggest suggestion powershell pwsh powershell 7 profile import-module feedback provider experimental feature pscommandnotfoundsuggestion psfeedbackprovider microsoft.winget.commandnotfound missing command package powertoys clone enable disable hook winget-suggest 搵唔到指令 找不到命令 建議 套件 掛鈎 設定檔 啟用 停用 實驗功能" },
    };

    public static IEnumerable<ModuleInfo> Search(string query)
    {
        if (string.IsNullOrWhiteSpace(query)) return All;
        var q = query.Trim().ToLowerInvariant();
        return All.Where(m => m.Haystack.Contains(q));
    }
}
