using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.UI.Text;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Media;
using WinForge.Catalog;
using WinForge.Controls;
using WinForge.Models;
using WinForge.Services;

namespace WinForge.Pages;

/// <summary>
/// Windows 終端機模組 · Windows Terminal module — three tabs:
///   1. Profiles editor: read / add / edit / delete / duplicate profiles in settings.json natively
///      (System.Text.Json DOM so unknown keys survive), set the default, pick paths via FileDialogs,
///      safe save (backup + atomic write).
///   2. Embedded terminal: a real shell (pwsh / cmd / wsl) hosted via ConPTY and rendered in the
///      shared <see cref="TerminalView"/> control (reused by the SSH module).
///   3. Quick launch: wt.exe convenience actions as hand-built control rows (no Controls/TweakCard):
///      bilingual title/description on the left, the matching WinUI control on the right; results and
///      errors go to the one persistent InfoBar shared with the profiles tab.
/// Missing Windows Terminal is detected and offered for one-click winget install.
/// 全部介面文字雙語（英文＋廣東話）。 All UI strings are bilingual (English + Cantonese).
/// </summary>
public sealed partial class TerminalModule : Page
{
    private const string WingetId = "Microsoft.WindowsTerminal";

    private string? _settingsPath;
    private JsonObject? _root;
    private bool _dirty;
    private bool _loadingFields;
    private bool _rowBusy; // guard so only one quick-launch action runs at a time
    private readonly ObservableCollection<ProfileRow> _rows = new();

    private ConPtySession? _pty;

    public TerminalModule()
    {
        InitializeComponent();
        Loc.I.LanguageChanged += OnLanguageChanged;
        Loaded += OnLoaded;
        Unloaded += OnUnloaded;
        Term.SizeChangedCols += (cols, rows) => _pty?.Resize((short)cols, (short)rows);
        Term.SendInput += t => _pty?.Write(t);
    }

    private void OnLanguageChanged(object? sender, EventArgs e)
    {
        Render();
        BuildOps(); // rebuild the quick-launch rows so their labels re-localise
    }

    private void OnUnloaded(object sender, RoutedEventArgs e)
    {
        Loc.I.LanguageChanged -= OnLanguageChanged;
        Loaded -= OnLoaded;
        Unloaded -= OnUnloaded;
        StopTerminal();
    }

    private string P(string en, string zh) => Loc.I.Pick(en, zh);

    private static string DisplayPath(string path)
    {
        var local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        if (!string.IsNullOrWhiteSpace(local) &&
            path.StartsWith(local, StringComparison.OrdinalIgnoreCase))
            return "%LOCALAPPDATA%" + path[local.Length..];

        var profile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        if (!string.IsNullOrWhiteSpace(profile) &&
            path.StartsWith(profile, StringComparison.OrdinalIgnoreCase))
            return "%USERPROFILE%" + path[profile.Length..];

        return path;
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        Render();
        BuildShellList();
        BuildOps();
        ReloadProfiles();
        UpdateInstallBar();
    }

    // ===================== Localised strings =====================

    private void Render()
    {
        Header.Title = "Windows Terminal · Windows 終端機";
        HeaderBlurb.Text = P("Edit Windows Terminal profiles natively (settings.json — backed up and written atomically so unknown keys are preserved), run a real shell embedded via ConPTY, and quick-launch wt.exe.",
            "原生編輯 Windows 終端機 profile（settings.json，會備份同原子寫入，保留未知欄位），用 ConPTY 喺 app 內開真正嘅 shell，仲可以快捷啟動 wt.exe。");

        ProfilesTab.Header = P("Profiles", "設定檔");
        TerminalTab.Header = P("Embedded terminal", "內嵌終端機");
        LaunchTab.Header = P("Quick launch", "快捷啟動");

        ReloadBtn.Content = P("Reload", "重新載入");
        AddBtn.Content = P("Add", "新增");
        SaveBtn.Content = P("Save", "儲存");
        EditorHint.Text = P("Select a profile on the left to edit it.", "喺左邊揀一個 profile 嚟編輯。");
        CmdPickBtn.Content = P("Browse", "瀏覽");
        DirPickBtn.Content = P("Browse", "瀏覽");
        IconPickBtn.Content = P("Browse", "瀏覽");
        SetDefaultBtn.Content = P("Set as default", "設為預設");
        DuplicateBtn.Content = P("Duplicate", "複製");
        DeleteBtn.Content = P("Delete", "刪除");
        LaunchProfileBtn.Content = P("Launch", "啟動");
        GeneratedNote.Text = P("This is an auto-generated profile (WSL / Visual Studio). Editing it is allowed but may be regenerated by Windows Terminal.",
            "呢個係自動產生嘅 profile（WSL／Visual Studio）。可以改，但 Windows 終端機可能會重新產生。");

        StartTermBtn.Content = P("Start", "開始");
        StopTermBtn.Content = P("Stop", "停止");
        ClearTermBtn.Content = P("Clear", "清除");
        RefreshTermStatus();
    }

    // ===================== Install detection =====================

    private void UpdateInstallBar()
    {
        bool wt = WindowsTerminalService.WtAvailable();
        bool settings = WindowsTerminalService.SettingsExist();

        InstallBar.ActionButton = null;
        if (wt || settings)
        {
            InstallBar.IsOpen = false;
            InstallBar.Content = null;
            return;
        }

        InstallBar.Severity = Microsoft.UI.Xaml.Controls.InfoBarSeverity.Warning;
        InstallBar.Title = P("Windows Terminal not found", "搵唔到 Windows 終端機");
        InstallBar.Message = P("The profiles editor and wt.exe launch need Windows Terminal. Install it below with live progress; the embedded ConPTY terminal works without it.",
            "設定檔編輯器同 wt.exe 啟動需要 Windows 終端機。喺下面安裝（即時進度）；內嵌 ConPTY 終端機冇佢都用得。");
        if (InstallBar.Content is not InstallProgress)
            InstallBar.Content = EngineBars.AutoInstallProgress(WingetId,
                "Install Windows Terminal", "安裝 Windows 終端機",
                recheck: async () => { await System.Threading.Tasks.Task.Yield(); UpdateInstallBar(); ReloadProfiles(); },
                rescan: () => WindowsTerminalService.Resolve());
        InstallBar.IsOpen = true;
    }

    // ===================== Profiles tab =====================

    private void ReloadProfiles()
    {
        _rows.Clear();
        ProfileList.ItemsSource = _rows;
        _settingsPath = WindowsTerminalService.Resolve();
        _dirty = false;

        if (_settingsPath is null)
        {
            PathText.Text = P("No settings.json found.", "搵唔到 settings.json。");
            _root = null;
            FieldsPanel.Visibility = Visibility.Collapsed;
            EditorHint.Text = P("Windows Terminal is not installed, so there is no settings.json to edit. Install it above, or use the embedded terminal tab.",
                "未安裝 Windows 終端機，所以冇 settings.json 可以改。喺上面安裝，或者用內嵌終端機分頁。");
            return;
        }

        try
        {
            _root = WindowsTerminalService.Load(_settingsPath);
            PathText.Text = DisplayPath(_settingsPath);
            PopulateList();
            Info(InfoBarSeverity.Informational, P("Loaded", "已載入"),
                $"{_rows.Count} " + P("profiles", "個設定檔"));
        }
        catch (Exception ex)
        {
            _root = null;
            Info(InfoBarSeverity.Error, P("Failed to read settings.json", "讀 settings.json 失敗"), ex.Message);
        }
    }

    private void PopulateList()
    {
        _rows.Clear();
        if (_root is null) return;
        var def = WindowsTerminalService.DefaultProfile(_root);
        foreach (var p in WindowsTerminalService.Profiles(_root))
            _rows.Add(new ProfileRow(p, p.Guid == def));
    }

    private void RefreshDefaultStars()
    {
        if (_root is null) return;
        var def = WindowsTerminalService.DefaultProfile(_root);
        foreach (var r in _rows) r.SetDefault(r.Profile.Guid == def);
    }

    private ProfileRow? Selected => ProfileList.SelectedItem as ProfileRow;

    private void Reload_Click(object sender, RoutedEventArgs e)
    {
        if (_dirty)
        {
            // Soft warn but reload (user explicitly clicked).
        }
        ReloadProfiles();
    }

    private void ProfileList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        var row = Selected;
        if (row is null) { FieldsPanel.Visibility = Visibility.Collapsed; EditorHint.Visibility = Visibility.Visible; return; }
        EditorHint.Visibility = Visibility.Collapsed;
        FieldsPanel.Visibility = Visibility.Visible;
        LoadFields(row);
    }

    private void LoadFields(ProfileRow row)
    {
        _loadingFields = true;
        var p = row.Profile;
        NameBox.Text = p.Name;
        CmdBox.Text = p.CommandLine;
        DirBox.Text = p.StartingDirectory;
        IconBox.Text = p.Icon;
        FontBox.Text = p.FontFace;
        HiddenToggle.IsOn = p.Hidden;

        // Scheme dropdown: built-ins + any defined in the file + current value.
        var schemes = new List<string> { "" };
        schemes.AddRange(WindowsTerminalService.BuiltInSchemes);
        if (_root is not null) schemes.AddRange(WindowsTerminalService.SchemeNames(_root));
        if (!string.IsNullOrEmpty(p.ColorScheme) && !schemes.Contains(p.ColorScheme)) schemes.Add(p.ColorScheme);
        SchemeBox.ItemsSource = schemes.Distinct().ToList();
        SchemeBox.SelectedItem = string.IsNullOrEmpty(p.ColorScheme) ? "" : p.ColorScheme;

        GeneratedNote.Visibility = p.IsGenerated ? Visibility.Visible : Visibility.Collapsed;
        SetDefaultBtn.IsEnabled = !row.IsDefault;
        _loadingFields = false;
    }

    private void Field_Changed(object sender, object e)
    {
        if (_loadingFields) return;
        var row = Selected;
        if (row is null) return;
        var p = row.Profile;
        p.Name = NameBox.Text;
        p.CommandLine = CmdBox.Text;
        p.StartingDirectory = DirBox.Text;
        p.Icon = IconBox.Text;
        p.FontFace = FontBox.Text;
        p.ColorScheme = SchemeBox.SelectedItem as string ?? "";
        p.Hidden = HiddenToggle.IsOn;
        row.Refresh();
        _dirty = true;
    }

    private void Add_Click(object sender, RoutedEventArgs e)
    {
        if (_root is null)
        {
            // No settings.json — offer to create a minimal one.
            if (_settingsPath is null)
                _settingsPath = WindowsTerminalService.CandidatePaths()[0];
            _root = new JsonObject
            {
                ["$schema"] = "https://aka.ms/terminal-profiles-schema",
                ["profiles"] = new JsonObject { ["defaults"] = new JsonObject(), ["list"] = new JsonArray() },
                ["schemes"] = new JsonArray(),
                ["actions"] = new JsonArray(),
            };
            PathText.Text = DisplayPath(_settingsPath);
        }

        var prof = WindowsTerminalService.NewProfile(P("New profile", "新設定檔"),
            "%SystemRoot%\\System32\\cmd.exe");
        WindowsTerminalService.ProfileListArray(_root).Add(prof.Node);
        if (string.IsNullOrEmpty(WindowsTerminalService.DefaultProfile(_root)))
            WindowsTerminalService.SetDefaultProfile(_root, prof.Guid);

        var row = new ProfileRow(prof, false);
        _rows.Add(row);
        ProfileList.SelectedItem = row;
        _dirty = true;
        Info(InfoBarSeverity.Informational, P("Added", "已新增"), P("New profile created — edit it then Save.", "已建立新設定檔 — 改完撳儲存。"));
    }

    private void Duplicate_Click(object sender, RoutedEventArgs e)
    {
        var row = Selected;
        if (row is null || _root is null) return;
        var clone = WindowsTerminalService.Duplicate(row.Profile);
        WindowsTerminalService.ProfileListArray(_root).Add(clone.Node);
        var newRow = new ProfileRow(clone, false);
        _rows.Add(newRow);
        ProfileList.SelectedItem = newRow;
        _dirty = true;
        Info(InfoBarSeverity.Informational, P("Duplicated", "已複製"), clone.Name);
    }

    private async void Delete_Click(object sender, RoutedEventArgs e)
    {
        var row = Selected;
        if (row is null || _root is null) return;

        var dlg = new ContentDialog
        {
            XamlRoot = XamlRoot,
            Title = P("Delete profile?", "刪除設定檔？"),
            Content = P($"Remove \"{row.Profile.Name}\" from settings.json? This is applied when you Save.",
                $"由 settings.json 移除「{row.Profile.Name}」？撳儲存先生效。"),
            PrimaryButtonText = P("Delete", "刪除"),
            CloseButtonText = P("Cancel", "取消"),
            DefaultButton = ContentDialogButton.Close,
        };
        if (await dlg.ShowAsync() != ContentDialogResult.Primary) return;

        var arr = WindowsTerminalService.ProfileListArray(_root);
        for (int i = 0; i < arr.Count; i++)
        {
            if (arr[i] is JsonObject o && ReferenceEquals(o, row.Profile.Node))
            {
                arr.RemoveAt(i);
                break;
            }
        }
        _rows.Remove(row);
        FieldsPanel.Visibility = Visibility.Collapsed;
        EditorHint.Visibility = Visibility.Visible;
        _dirty = true;
        Info(InfoBarSeverity.Informational, P("Removed", "已移除"), P("Click Save to write the change.", "撳儲存先寫入更改。"));
    }

    private void SetDefault_Click(object sender, RoutedEventArgs e)
    {
        var row = Selected;
        if (row is null || _root is null) return;
        WindowsTerminalService.SetDefaultProfile(_root, row.Profile.Guid);
        RefreshDefaultStars();
        SetDefaultBtn.IsEnabled = false;
        _dirty = true;
        Info(InfoBarSeverity.Informational, P("Default set", "已設為預設"), row.Profile.Name);
    }

    private void Save_Click(object sender, RoutedEventArgs e)
    {
        if (_root is null || _settingsPath is null)
        {
            Info(InfoBarSeverity.Warning, P("Nothing to save", "冇嘢可以儲存"), P("There is no settings.json loaded.", "未載入任何 settings.json。"));
            return;
        }
        try
        {
            var backup = WindowsTerminalService.Save(_settingsPath, _root);
            _dirty = false;
            var msg = string.IsNullOrEmpty(backup)
                ? P("Saved (new file).", "已儲存（新檔）。")
                : P($"Saved. Backup: {Path.GetFileName(backup)}", $"已儲存。備份：{Path.GetFileName(backup)}");
            Info(InfoBarSeverity.Success, P("Saved", "已儲存"), msg);
        }
        catch (UnauthorizedAccessException)
        {
            Info(InfoBarSeverity.Error, P("Save failed", "儲存失敗"), P("Access denied writing settings.json.", "寫入 settings.json 被拒。"));
        }
        catch (Exception ex)
        {
            Info(InfoBarSeverity.Error, P("Save failed", "儲存失敗"), ex.Message);
        }
    }

    private async void PickCmd_Click(object sender, RoutedEventArgs e)
    {
        var path = await FileDialogs.OpenFileAsync(".exe", ".bat", ".cmd");
        if (path is not null) { CmdBox.Text = path; Field_Changed(sender, e); }
    }

    private async void PickDir_Click(object sender, RoutedEventArgs e)
    {
        var dir = await FileDialogs.OpenFolderAsync(P("Pick starting directory", "揀起始目錄"));
        if (dir is not null) { DirBox.Text = dir; Field_Changed(sender, e); }
    }

    private async void PickIcon_Click(object sender, RoutedEventArgs e)
    {
        var path = await FileDialogs.OpenFileAsync(".ico", ".png", ".jpg", ".exe", ".dll");
        if (path is not null) { IconBox.Text = path; Field_Changed(sender, e); }
    }

    private async void LaunchProfile_Click(object sender, RoutedEventArgs e)
    {
        var row = Selected;
        if (row is null) return;
        if (!WindowsTerminalService.WtAvailable())
        {
            Info(InfoBarSeverity.Warning, P("wt.exe not found", "搵唔到 wt.exe"), P("Install Windows Terminal first.", "請先安裝 Windows 終端機。"));
            return;
        }
        var args = WindowsTerminalService.BuildLaunchArgs(row.Profile.Name, row.Profile.StartingDirectory, newTab: true);
        var r = await ShellRunner.Run("wt.exe", args);
        Info(r.Success ? InfoBarSeverity.Success : InfoBarSeverity.Error,
            r.Success ? P("Launched", "已啟動") : P("Failed", "失敗"), $"wt {args}");
    }

    // ===================== Embedded terminal tab =====================

    private void BuildShellList()
    {
        var shells = new List<ShellOption>
        {
            new("Windows PowerShell", "powershell.exe"),
            new("Command Prompt · 命令提示字元", "cmd.exe"),
        };
        // pwsh (PowerShell 7) if present.
        var pwsh = ResolveOnPath("pwsh.exe");
        if (pwsh is not null) shells.Insert(0, new("PowerShell 7 (pwsh)", pwsh));
        // WSL default distro.
        if (ResolveOnPath("wsl.exe") is not null) shells.Add(new("WSL · Linux 子系統", "wsl.exe"));

        ShellBox.ItemsSource = shells;
        ShellBox.DisplayMemberPath = "Label";
        ShellBox.SelectedIndex = 0;
    }

    private static string? ResolveOnPath(string exe)
    {
        var pathVar = Environment.GetEnvironmentVariable("PATH") ?? "";
        foreach (var dir in pathVar.Split(Path.PathSeparator))
        {
            try
            {
                if (string.IsNullOrWhiteSpace(dir)) continue;
                var c = Path.Combine(dir.Trim(), exe);
                if (File.Exists(c)) return c;
            }
            catch { }
        }
        // System32 fallback for wsl.exe / powershell.exe.
        var sys = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), exe);
        return File.Exists(sys) ? sys : null;
    }

    private void StartTerm_Click(object sender, RoutedEventArgs e)
    {
        if (_pty is not null) StopTerminal();
        if (ShellBox.SelectedItem is not ShellOption opt) return;

        Term.ClearScreen();
        try
        {
            _pty = new ConPtySession();
            _pty.OutputReceived += s => Term.Feed(s);
            _pty.Exited += code => DispatcherQueue.TryEnqueue(() =>
            {
                Term.Feed($"\r\n[{P("process exited", "程序結束")}: {code}]\r\n");
                StopTerminal();
            });
            _pty.Start(opt.CommandLine, (short)Term.Columns, (short)Term.Rows,
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile));
            StartTermBtn.IsEnabled = false;
            StopTermBtn.IsEnabled = true;
            Term.Focus(FocusState.Programmatic);
            RefreshTermStatus();
        }
        catch (Exception ex)
        {
            _pty = null;
            Info(InfoBarSeverity.Error, P("Could not start shell", "開唔到 shell"), ex.Message);
            RefreshTermStatus();
        }
    }

    private void StopTerm_Click(object sender, RoutedEventArgs e) => StopTerminal();

    private void StopTerminal()
    {
        try { _pty?.Dispose(); } catch { }
        _pty = null;
        if (StartTermBtn is not null) StartTermBtn.IsEnabled = true;
        if (StopTermBtn is not null) StopTermBtn.IsEnabled = false;
        RefreshTermStatus();
    }

    private void ClearTerm_Click(object sender, RoutedEventArgs e) => Term.ClearScreen();

    private void RefreshTermStatus() => RefreshTermStatusCore();

    private void RefreshTermStatusCore()
    {
        if (TermStatus is null) return;
        TermStatus.Text = _pty is { IsRunning: true }
            ? P("Running — click the terminal and type. Ctrl+C interrupts.", "執行中 — 撳一下終端機就可以打字。Ctrl+C 中斷。")
            : P("Stopped.", "已停止。");
    }

    // ===================== Quick launch tab =====================

    private void BuildOps()
    {
        OpsPanel.Children.Clear();
        bool first = true;
        foreach (var op in TerminalOperations.All())
        {
            if (!first) OpsPanel.Children.Add(BuildDivider());
            first = false;
            OpsPanel.Children.Add(BuildRow(op));
        }
    }

    // ---- One clean row: bilingual title + description on the left, control on the right ----
    private FrameworkElement BuildRow(TweakDefinition op)
    {
        var grid = new Grid { Padding = new Thickness(0, 12, 0, 12) };
        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });

        var text = new StackPanel { Spacing = 2, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(0, 0, 16, 0) };

        text.Children.Add(new TextBlock { Text = op.Title.Primary, FontWeight = FontWeights.SemiBold, TextWrapping = TextWrapping.Wrap });

        if (!string.IsNullOrWhiteSpace(op.Title.Secondary))
            text.Children.Add(new TextBlock
            {
                Text = op.Title.Secondary,
                FontSize = 12,
                Foreground = (Brush)Application.Current.Resources["TextFillColorSecondaryBrush"],
                TextWrapping = TextWrapping.Wrap,
            });

        if (!string.IsNullOrWhiteSpace(op.Description.Primary))
            text.Children.Add(new TextBlock
            {
                Text = op.Description.Primary,
                FontSize = 13,
                Foreground = (Brush)Application.Current.Resources["TextFillColorSecondaryBrush"],
                TextWrapping = TextWrapping.Wrap,
                Margin = new Thickness(0, 2, 0, 0),
            });
        if (!string.IsNullOrWhiteSpace(op.Description.Secondary))
            text.Children.Add(new TextBlock
            {
                Text = op.Description.Secondary,
                FontSize = 12,
                Foreground = (Brush)Application.Current.Resources["TextFillColorTertiaryBrush"],
                TextWrapping = TextWrapping.Wrap,
            });

        // Small admin / restart hints so nothing from the card chrome is lost.
        var hint = HintText(op);
        if (hint is not null)
            text.Children.Add(new TextBlock
            {
                Text = hint,
                FontSize = 11,
                Foreground = (Brush)Application.Current.Resources["TextFillColorTertiaryBrush"],
                TextWrapping = TextWrapping.Wrap,
                Margin = new Thickness(0, 2, 0, 0),
            });

        Grid.SetColumn(text, 0);
        grid.Children.Add(text);

        var control = BuildControl(op);
        control.VerticalAlignment = VerticalAlignment.Center;
        Grid.SetColumn(control, 1);
        grid.Children.Add(control);

        return grid;
    }

    private string? HintText(TweakDefinition op)
    {
        var parts = new List<string>();
        if (op.RequiresAdmin) parts.Add(P("Admin", "管理員"));
        switch (op.Restart)
        {
            case RestartScope.Explorer: parts.Add(P("Restart Explorer", "重啟檔案總管")); break;
            case RestartScope.SignOut: parts.Add(P("Sign out", "登出")); break;
            case RestartScope.Reboot: parts.Add(P("Reboot", "重新開機")); break;
        }
        return parts.Count == 0 ? null : string.Join(" · ", parts);
    }

    private Border BuildDivider() => new()
    {
        Height = 1,
        Background = (Brush)Application.Current.Resources["CardStrokeColorDefaultBrush"],
        Opacity = 0.6,
    };

    /// <summary>對應每種 Tweak 種類砌一個真控件 · Build the matching WinUI control for the tweak kind.</summary>
    private FrameworkElement BuildControl(TweakDefinition op) => op.Kind switch
    {
        TweakKind.Toggle => BuildToggle(op),
        TweakKind.Choice => BuildChoice(op),
        TweakKind.Slider => BuildSlider(op),
        TweakKind.Number => BuildNumber(op),
        TweakKind.Info => BuildInfo(op),
        _ => BuildAction(op), // Action (and any other kind) → button
    };

    // ---------------- Action → Button awaiting RunAsync ----------------
    private FrameworkElement BuildAction(TweakDefinition op)
    {
        var label = op.ActionLabel?.Get(Loc.I.Language) ?? P("Run", "執行");
        var btn = new Button { Content = label, MinWidth = 110 };
        if (op.ActionLabel is not null)
            ToolTipService.SetToolTip(btn, $"{op.ActionLabel.En} · {op.ActionLabel.Zh}");

        btn.Click += async (_, _) =>
        {
            if (_rowBusy || op.RunAsync is null) return;
            if (op.Destructive && !await ConfirmAsync(op)) return;

            _rowBusy = true;
            btn.IsEnabled = false;
            var restore = btn.Content;
            btn.Content = new ProgressRing { IsActive = true, Width = 18, Height = 18 };
            try
            {
                var result = await op.RunAsync(CancellationToken.None);
                ShowResult(op, result);
            }
            catch (Exception ex)
            {
                ShowError(op, ex);
            }
            finally
            {
                btn.Content = restore;
                btn.IsEnabled = true;
                _rowBusy = false;
            }
        };
        return btn;
    }

    // ---------------- Toggle → ToggleSwitch ----------------
    private FrameworkElement BuildToggle(TweakDefinition op)
    {
        var toggle = new ToggleSwitch { OnContent = "On · 開", OffContent = "Off · 熄" };
        bool suppress = true;
        try { toggle.IsOn = op.GetIsOn?.Invoke() ?? false; } catch { /* show as off */ }
        suppress = false;

        toggle.Toggled += (_, _) =>
        {
            if (suppress || op.SetIsOn is null) return;
            try { op.SetIsOn(toggle.IsOn); ShowApplied(op); }
            catch (Exception ex)
            {
                suppress = true;
                try { toggle.IsOn = op.GetIsOn?.Invoke() ?? false; } catch { /* ignore */ }
                suppress = false;
                ShowError(op, ex);
            }
        };
        return toggle;
    }

    // ---------------- Choice → ComboBox ----------------
    private FrameworkElement BuildChoice(TweakDefinition op)
    {
        var combo = new ComboBox { MinWidth = 170 };
        if (op.Choices is not null)
            foreach (var c in op.Choices)
                combo.Items.Add(new ComboBoxItem { Content = c.Label.Get(Loc.I.Language), Tag = c.Value });

        bool suppress = true;
        try { SelectComboToCurrent(combo, op); }
        catch { /* leave unselected */ }
        suppress = false;

        combo.SelectionChanged += (_, _) =>
        {
            if (suppress || op.SetChoice is null) return;
            if (combo.SelectedItem is ComboBoxItem item && item.Tag is string val)
            {
                try { op.SetChoice(val); ShowApplied(op); }
                catch (Exception ex)
                {
                    ShowError(op, ex);
                    suppress = true;
                    try { SelectComboToCurrent(combo, op); } catch { /* ignore */ }
                    suppress = false;
                }
            }
        };
        return combo;
    }

    private static void SelectComboToCurrent(ComboBox combo, TweakDefinition op)
    {
        var cur = op.GetCurrentChoice?.Invoke();
        if (cur is null || op.Choices is null) return;
        for (int i = 0; i < op.Choices.Count; i++)
            if (string.Equals(op.Choices[i].Value, cur, StringComparison.OrdinalIgnoreCase))
            { combo.SelectedIndex = i; return; }
    }

    // ---------------- Slider → Slider + value label ----------------
    private FrameworkElement BuildSlider(TweakDefinition op)
    {
        var panel = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 10, VerticalAlignment = VerticalAlignment.Center };
        var slider = new Slider
        {
            Minimum = op.Min,
            Maximum = op.Max,
            StepFrequency = op.Step,
            Width = 160,
            VerticalAlignment = VerticalAlignment.Center,
        };
        var valueLabel = new TextBlock
        {
            MinWidth = 56,
            VerticalAlignment = VerticalAlignment.Center,
            Foreground = (Brush)Application.Current.Resources["TextFillColorSecondaryBrush"],
        };

        string Fmt(double v)
        {
            bool whole = op.Step >= 1 && Math.Abs(op.Step % 1) < 1e-9;
            string num = whole ? Math.Round(v).ToString(CultureInfo.InvariantCulture)
                               : v.ToString("0.###", CultureInfo.InvariantCulture);
            return op.Unit is null ? num : $"{num} {op.Unit.Primary}";
        }
        double Clamp(double v) => Math.Max(op.Min, Math.Min(op.Max, v));

        bool suppress = true;
        try { slider.Value = Clamp(op.GetNumber?.Invoke() ?? op.Min); } catch { slider.Value = op.Min; }
        suppress = false;
        valueLabel.Text = Fmt(slider.Value);

        slider.ValueChanged += (_, e) =>
        {
            valueLabel.Text = Fmt(e.NewValue);
            if (suppress || op.SetNumber is null) return;
            try { op.SetNumber(e.NewValue); ShowApplied(op); }
            catch (Exception ex)
            {
                ShowError(op, ex);
                suppress = true;
                try { slider.Value = Clamp(op.GetNumber?.Invoke() ?? op.Min); } catch { /* ignore */ }
                suppress = false;
            }
        };

        panel.Children.Add(slider);
        panel.Children.Add(valueLabel);
        return panel;
    }

    // ---------------- Number → NumberBox ----------------
    private FrameworkElement BuildNumber(TweakDefinition op)
    {
        var box = new NumberBox
        {
            Minimum = op.Min,
            Maximum = op.Max,
            SmallChange = op.Step,
            LargeChange = op.Step,
            SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Inline,
            MinWidth = 140,
            ValidationMode = NumberBoxValidationMode.InvalidInputOverwritten,
        };
        double Clamp(double v) => Math.Max(op.Min, Math.Min(op.Max, v));

        bool suppress = true;
        try { box.Value = Clamp(op.GetNumber?.Invoke() ?? op.Min); } catch { box.Value = op.Min; }
        suppress = false;

        box.ValueChanged += (_, e) =>
        {
            if (suppress || op.SetNumber is null) return;
            if (double.IsNaN(e.NewValue)) return;
            try { op.SetNumber(e.NewValue); ShowApplied(op); }
            catch (Exception ex)
            {
                ShowError(op, ex);
                suppress = true;
                try { box.Value = Clamp(op.GetNumber?.Invoke() ?? op.Min); } catch { /* ignore */ }
                suppress = false;
            }
        };
        return box;
    }

    // ---------------- Info → refreshable TextBlock ----------------
    private FrameworkElement BuildInfo(TweakDefinition op)
    {
        string Safe() { try { return op.GetInfo?.Invoke() ?? "—"; } catch { return "—"; } }

        var panel = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 6, VerticalAlignment = VerticalAlignment.Center };
        var info = new TextBlock
        {
            Text = Safe(),
            IsTextSelectionEnabled = true,
            TextWrapping = TextWrapping.Wrap,
            MaxWidth = 300,
            HorizontalTextAlignment = TextAlignment.Right,
            VerticalAlignment = VerticalAlignment.Center,
        };
        var refresh = new Button { Content = new FontIcon { Glyph = "", FontSize = 14 }, Padding = new Thickness(8) };
        ToolTipService.SetToolTip(refresh, "Refresh · 重新整理");
        refresh.Click += (_, _) => info.Text = Safe();
        panel.Children.Add(info);
        panel.Children.Add(refresh);
        return panel;
    }

    // ---------------- Confirmation for destructive actions ----------------
    private async Task<bool> ConfirmAsync(TweakDefinition op)
    {
        var dlg = new ContentDialog
        {
            XamlRoot = XamlRoot,
            Title = P("Are you sure?", "確定嗎？"),
            Content = $"{op.Title.En}\n{op.Title.Zh}\n\n" +
                      "This action may be hard to undo.\n呢個動作可能難以復原。",
            PrimaryButtonText = P("Proceed", "繼續"),
            CloseButtonText = P("Cancel", "取消"),
            DefaultButton = ContentDialogButton.Close,
        };
        try { return await dlg.ShowAsync() == ContentDialogResult.Primary; }
        catch { return false; }
    }

    // ---------------- Shared row result / status (routes through the persistent ResultBar) ----------------
    private void ShowResult(TweakDefinition op, TweakResult result)
    {
        ResultBar.Severity = result.Success ? InfoBarSeverity.Success : InfoBarSeverity.Error;
        ResultBar.Title = result.Success ? P("Done", "完成") : P("Failed", "失敗");
        ResultBar.Message = result.Message is null
            ? (result.Output ?? string.Empty)
            : result.Message.Get(Loc.I.Language);
        ResultBar.IsOpen = true;
    }

    private void ShowApplied(TweakDefinition op)
    {
        string en = "Applied.", zh = "已套用。";
        switch (op.Restart)
        {
            case RestartScope.Explorer: en = "Applied. Restart Explorer to see the change."; zh = "已套用。重啟檔案總管就睇到變化。"; break;
            case RestartScope.SignOut: en = "Applied. Sign out and back in to take effect."; zh = "已套用。登出再登入後生效。"; break;
            case RestartScope.Reboot: en = "Applied. Reboot to take effect."; zh = "已套用。重新開機後生效。"; break;
        }
        ResultBar.Severity = InfoBarSeverity.Success;
        ResultBar.Title = P("Done", "完成");
        ResultBar.Message = P(en, zh);
        ResultBar.IsOpen = true;
    }

    private void ShowError(TweakDefinition op, Exception ex)
    {
        bool needAdmin = op.RequiresAdmin && !AdminHelper.IsElevated;
        ResultBar.Severity = InfoBarSeverity.Error;
        ResultBar.Title = P("Failed", "失敗");
        ResultBar.Message = needAdmin
            ? P("This change needs administrator rights.", "呢項更改需要管理員權限。")
            : ex.Message;
        ResultBar.IsOpen = true;
    }

    // ===================== Helpers =====================

    private void Info(InfoBarSeverity sev, string title, string msg)
    {
        ResultBar.Severity = sev;
        ResultBar.Title = title;
        ResultBar.Message = msg;
        ResultBar.IsOpen = true;
    }

    private sealed record ShellOption(string Label, string CommandLine);

    /// <summary>列表項目視圖模型 · A profile row bound to the ListView.</summary>
    public sealed class ProfileRow : System.ComponentModel.INotifyPropertyChanged
    {
        public WtProfile Profile { get; }
        public bool IsDefault { get; private set; }

        public ProfileRow(WtProfile p, bool isDefault) { Profile = p; IsDefault = isDefault; }

        public string DisplayName => string.IsNullOrWhiteSpace(Profile.Name) ? "(unnamed)" : Profile.Name;

        public string SubText
        {
            get
            {
                var bits = new List<string>();
                if (Profile.Hidden) bits.Add("hidden · 隱藏");
                if (Profile.IsGenerated) bits.Add(Profile.Source);
                var cmd = Profile.CommandLine;
                if (!string.IsNullOrEmpty(cmd)) bits.Add(cmd);
                return string.Join("  ·  ", bits);
            }
        }

        public Visibility DefaultStar => IsDefault ? Visibility.Visible : Visibility.Collapsed;

        public void SetDefault(bool v) { IsDefault = v; Raise(nameof(DefaultStar)); }
        public void Refresh() { Raise(nameof(DisplayName)); Raise(nameof(SubText)); }

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
        private void Raise(string n) => PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(n));
    }
}
