#include "TextAnalysis.h"

#include "TextDiff.h"

#include <Windows.h>
#include <icu.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cwchar>
#include <limits>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#pragma comment(lib, "icu.lib")

namespace
{
    using namespace winforge::core::textanalysis;

    struct LowerRange
    {
        std::uint32_t first;
        std::uint32_t last;
        std::uint32_t step;
        std::int32_t delta;
    };

    struct LowerPair
    {
        std::uint32_t from;
        std::uint32_t to;
    };

    struct CodeRange
    {
        std::uint32_t first;
        std::uint32_t last;
    };

    // Generated by exhaustively probing the shipping .NET 11 managed oracle.
    // Invariant simple casing never expands a scalar and is locale-independent.
    constexpr std::array<LowerRange, 66> LowerRanges{
        LowerRange{ 0x41u, 0x5Au, 1u, 32 },
        LowerRange{ 0xC0u, 0xD6u, 1u, 32 },
        LowerRange{ 0xD8u, 0xDEu, 1u, 32 },
        LowerRange{ 0x100u, 0x12Eu, 2u, 1 },
        LowerRange{ 0x132u, 0x136u, 2u, 1 },
        LowerRange{ 0x139u, 0x147u, 2u, 1 },
        LowerRange{ 0x14Au, 0x176u, 2u, 1 },
        LowerRange{ 0x179u, 0x17Du, 2u, 1 },
        LowerRange{ 0x1A0u, 0x1A4u, 2u, 1 },
        LowerRange{ 0x1CBu, 0x1DBu, 2u, 1 },
        LowerRange{ 0x1DEu, 0x1EEu, 2u, 1 },
        LowerRange{ 0x1F8u, 0x21Eu, 2u, 1 },
        LowerRange{ 0x222u, 0x232u, 2u, 1 },
        LowerRange{ 0x246u, 0x24Eu, 2u, 1 },
        LowerRange{ 0x388u, 0x38Au, 1u, 37 },
        LowerRange{ 0x391u, 0x3A1u, 1u, 32 },
        LowerRange{ 0x3A3u, 0x3ABu, 1u, 32 },
        LowerRange{ 0x3D8u, 0x3EEu, 2u, 1 },
        LowerRange{ 0x3FDu, 0x3FFu, 1u, -130 },
        LowerRange{ 0x400u, 0x40Fu, 1u, 80 },
        LowerRange{ 0x410u, 0x42Fu, 1u, 32 },
        LowerRange{ 0x460u, 0x480u, 2u, 1 },
        LowerRange{ 0x48Au, 0x4BEu, 2u, 1 },
        LowerRange{ 0x4C1u, 0x4CDu, 2u, 1 },
        LowerRange{ 0x4D0u, 0x52Eu, 2u, 1 },
        LowerRange{ 0x531u, 0x556u, 1u, 48 },
        LowerRange{ 0x10A0u, 0x10C5u, 1u, 7264 },
        LowerRange{ 0x13A0u, 0x13EFu, 1u, 38864 },
        LowerRange{ 0x13F0u, 0x13F5u, 1u, 8 },
        LowerRange{ 0x1C90u, 0x1CBAu, 1u, -3008 },
        LowerRange{ 0x1CBDu, 0x1CBFu, 1u, -3008 },
        LowerRange{ 0x1E00u, 0x1E94u, 2u, 1 },
        LowerRange{ 0x1EA0u, 0x1EFEu, 2u, 1 },
        LowerRange{ 0x1F08u, 0x1F0Fu, 1u, -8 },
        LowerRange{ 0x1F18u, 0x1F1Du, 1u, -8 },
        LowerRange{ 0x1F28u, 0x1F2Fu, 1u, -8 },
        LowerRange{ 0x1F38u, 0x1F3Fu, 1u, -8 },
        LowerRange{ 0x1F48u, 0x1F4Du, 1u, -8 },
        LowerRange{ 0x1F59u, 0x1F5Fu, 2u, -8 },
        LowerRange{ 0x1F68u, 0x1F6Fu, 1u, -8 },
        LowerRange{ 0x1F88u, 0x1F8Fu, 1u, -8 },
        LowerRange{ 0x1F98u, 0x1F9Fu, 1u, -8 },
        LowerRange{ 0x1FA8u, 0x1FAFu, 1u, -8 },
        LowerRange{ 0x1FC8u, 0x1FCBu, 1u, -86 },
        LowerRange{ 0x2160u, 0x216Fu, 1u, 16 },
        LowerRange{ 0x24B6u, 0x24CFu, 1u, 26 },
        LowerRange{ 0x2C00u, 0x2C2Fu, 1u, 48 },
        LowerRange{ 0x2C67u, 0x2C6Bu, 2u, 1 },
        LowerRange{ 0x2C80u, 0x2CE2u, 2u, 1 },
        LowerRange{ 0xA640u, 0xA66Cu, 2u, 1 },
        LowerRange{ 0xA680u, 0xA69Au, 2u, 1 },
        LowerRange{ 0xA722u, 0xA72Eu, 2u, 1 },
        LowerRange{ 0xA732u, 0xA76Eu, 2u, 1 },
        LowerRange{ 0xA77Eu, 0xA786u, 2u, 1 },
        LowerRange{ 0xA796u, 0xA7A8u, 2u, 1 },
        LowerRange{ 0xA7B4u, 0xA7C2u, 2u, 1 },
        LowerRange{ 0xFF21u, 0xFF3Au, 1u, 32 },
        LowerRange{ 0x10400u, 0x10427u, 1u, 40 },
        LowerRange{ 0x104B0u, 0x104D3u, 1u, 40 },
        LowerRange{ 0x10570u, 0x1057Au, 1u, 39 },
        LowerRange{ 0x1057Cu, 0x1058Au, 1u, 39 },
        LowerRange{ 0x1058Cu, 0x10592u, 1u, 39 },
        LowerRange{ 0x10C80u, 0x10CB2u, 1u, 64 },
        LowerRange{ 0x118A0u, 0x118BFu, 1u, 32 },
        LowerRange{ 0x16E40u, 0x16E5Fu, 1u, 32 },
        LowerRange{ 0x1E900u, 0x1E921u, 1u, 34 },
    };

    constexpr std::array<LowerPair, 137> LowerPairs{
        LowerPair{ 0x178u, 0xFFu },
        LowerPair{ 0x181u, 0x253u },
        LowerPair{ 0x182u, 0x183u },
        LowerPair{ 0x184u, 0x185u },
        LowerPair{ 0x186u, 0x254u },
        LowerPair{ 0x187u, 0x188u },
        LowerPair{ 0x189u, 0x256u },
        LowerPair{ 0x18Au, 0x257u },
        LowerPair{ 0x18Bu, 0x18Cu },
        LowerPair{ 0x18Eu, 0x1DDu },
        LowerPair{ 0x18Fu, 0x259u },
        LowerPair{ 0x190u, 0x25Bu },
        LowerPair{ 0x191u, 0x192u },
        LowerPair{ 0x193u, 0x260u },
        LowerPair{ 0x194u, 0x263u },
        LowerPair{ 0x196u, 0x269u },
        LowerPair{ 0x197u, 0x268u },
        LowerPair{ 0x198u, 0x199u },
        LowerPair{ 0x19Cu, 0x26Fu },
        LowerPair{ 0x19Du, 0x272u },
        LowerPair{ 0x19Fu, 0x275u },
        LowerPair{ 0x1A6u, 0x280u },
        LowerPair{ 0x1A7u, 0x1A8u },
        LowerPair{ 0x1A9u, 0x283u },
        LowerPair{ 0x1ACu, 0x1ADu },
        LowerPair{ 0x1AEu, 0x288u },
        LowerPair{ 0x1AFu, 0x1B0u },
        LowerPair{ 0x1B1u, 0x28Au },
        LowerPair{ 0x1B2u, 0x28Bu },
        LowerPair{ 0x1B3u, 0x1B4u },
        LowerPair{ 0x1B5u, 0x1B6u },
        LowerPair{ 0x1B7u, 0x292u },
        LowerPair{ 0x1B8u, 0x1B9u },
        LowerPair{ 0x1BCu, 0x1BDu },
        LowerPair{ 0x1C4u, 0x1C6u },
        LowerPair{ 0x1C5u, 0x1C6u },
        LowerPair{ 0x1C7u, 0x1C9u },
        LowerPair{ 0x1C8u, 0x1C9u },
        LowerPair{ 0x1CAu, 0x1CCu },
        LowerPair{ 0x1F1u, 0x1F3u },
        LowerPair{ 0x1F2u, 0x1F3u },
        LowerPair{ 0x1F4u, 0x1F5u },
        LowerPair{ 0x1F6u, 0x195u },
        LowerPair{ 0x1F7u, 0x1BFu },
        LowerPair{ 0x220u, 0x19Eu },
        LowerPair{ 0x23Au, 0x2C65u },
        LowerPair{ 0x23Bu, 0x23Cu },
        LowerPair{ 0x23Du, 0x19Au },
        LowerPair{ 0x23Eu, 0x2C66u },
        LowerPair{ 0x241u, 0x242u },
        LowerPair{ 0x243u, 0x180u },
        LowerPair{ 0x244u, 0x289u },
        LowerPair{ 0x245u, 0x28Cu },
        LowerPair{ 0x370u, 0x371u },
        LowerPair{ 0x372u, 0x373u },
        LowerPair{ 0x376u, 0x377u },
        LowerPair{ 0x37Fu, 0x3F3u },
        LowerPair{ 0x386u, 0x3ACu },
        LowerPair{ 0x38Cu, 0x3CCu },
        LowerPair{ 0x38Eu, 0x3CDu },
        LowerPair{ 0x38Fu, 0x3CEu },
        LowerPair{ 0x3CFu, 0x3D7u },
        LowerPair{ 0x3F4u, 0x3B8u },
        LowerPair{ 0x3F7u, 0x3F8u },
        LowerPair{ 0x3F9u, 0x3F2u },
        LowerPair{ 0x3FAu, 0x3FBu },
        LowerPair{ 0x4C0u, 0x4CFu },
        LowerPair{ 0x10C7u, 0x2D27u },
        LowerPair{ 0x10CDu, 0x2D2Du },
        LowerPair{ 0x1E9Eu, 0xDFu },
        LowerPair{ 0x1FB8u, 0x1FB0u },
        LowerPair{ 0x1FB9u, 0x1FB1u },
        LowerPair{ 0x1FBAu, 0x1F70u },
        LowerPair{ 0x1FBBu, 0x1F71u },
        LowerPair{ 0x1FBCu, 0x1FB3u },
        LowerPair{ 0x1FCCu, 0x1FC3u },
        LowerPair{ 0x1FD8u, 0x1FD0u },
        LowerPair{ 0x1FD9u, 0x1FD1u },
        LowerPair{ 0x1FDAu, 0x1F76u },
        LowerPair{ 0x1FDBu, 0x1F77u },
        LowerPair{ 0x1FE8u, 0x1FE0u },
        LowerPair{ 0x1FE9u, 0x1FE1u },
        LowerPair{ 0x1FEAu, 0x1F7Au },
        LowerPair{ 0x1FEBu, 0x1F7Bu },
        LowerPair{ 0x1FECu, 0x1FE5u },
        LowerPair{ 0x1FF8u, 0x1F78u },
        LowerPair{ 0x1FF9u, 0x1F79u },
        LowerPair{ 0x1FFAu, 0x1F7Cu },
        LowerPair{ 0x1FFBu, 0x1F7Du },
        LowerPair{ 0x1FFCu, 0x1FF3u },
        LowerPair{ 0x2126u, 0x3C9u },
        LowerPair{ 0x212Au, 0x6Bu },
        LowerPair{ 0x212Bu, 0xE5u },
        LowerPair{ 0x2132u, 0x214Eu },
        LowerPair{ 0x2183u, 0x2184u },
        LowerPair{ 0x2C60u, 0x2C61u },
        LowerPair{ 0x2C62u, 0x26Bu },
        LowerPair{ 0x2C63u, 0x1D7Du },
        LowerPair{ 0x2C64u, 0x27Du },
        LowerPair{ 0x2C6Du, 0x251u },
        LowerPair{ 0x2C6Eu, 0x271u },
        LowerPair{ 0x2C6Fu, 0x250u },
        LowerPair{ 0x2C70u, 0x252u },
        LowerPair{ 0x2C72u, 0x2C73u },
        LowerPair{ 0x2C75u, 0x2C76u },
        LowerPair{ 0x2C7Eu, 0x23Fu },
        LowerPair{ 0x2C7Fu, 0x240u },
        LowerPair{ 0x2CEBu, 0x2CECu },
        LowerPair{ 0x2CEDu, 0x2CEEu },
        LowerPair{ 0x2CF2u, 0x2CF3u },
        LowerPair{ 0xA779u, 0xA77Au },
        LowerPair{ 0xA77Bu, 0xA77Cu },
        LowerPair{ 0xA77Du, 0x1D79u },
        LowerPair{ 0xA78Bu, 0xA78Cu },
        LowerPair{ 0xA78Du, 0x265u },
        LowerPair{ 0xA790u, 0xA791u },
        LowerPair{ 0xA792u, 0xA793u },
        LowerPair{ 0xA7AAu, 0x266u },
        LowerPair{ 0xA7ABu, 0x25Cu },
        LowerPair{ 0xA7ACu, 0x261u },
        LowerPair{ 0xA7ADu, 0x26Cu },
        LowerPair{ 0xA7AEu, 0x26Au },
        LowerPair{ 0xA7B0u, 0x29Eu },
        LowerPair{ 0xA7B1u, 0x287u },
        LowerPair{ 0xA7B2u, 0x29Du },
        LowerPair{ 0xA7B3u, 0xAB53u },
        LowerPair{ 0xA7C4u, 0xA794u },
        LowerPair{ 0xA7C5u, 0x282u },
        LowerPair{ 0xA7C6u, 0x1D8Eu },
        LowerPair{ 0xA7C7u, 0xA7C8u },
        LowerPair{ 0xA7C9u, 0xA7CAu },
        LowerPair{ 0xA7D0u, 0xA7D1u },
        LowerPair{ 0xA7D6u, 0xA7D7u },
        LowerPair{ 0xA7D8u, 0xA7D9u },
        LowerPair{ 0xA7F5u, 0xA7F6u },
        LowerPair{ 0x10594u, 0x105BBu },
        LowerPair{ 0x10595u, 0x105BCu },
    };

    // Exact .NET 11 char.IsLetterOrDigit(char) BMP ranges. The managed
    // tokenizers enumerate UTF-16 code units, so supplementary letters do not
    // combine on these paths.
    constexpr std::array<CodeRange, 401> LetterOrDigitRanges{
        CodeRange{ 0x30u, 0x39u },
        CodeRange{ 0x41u, 0x5Au },
        CodeRange{ 0x61u, 0x7Au },
        CodeRange{ 0xAAu, 0xAAu },
        CodeRange{ 0xB5u, 0xB5u },
        CodeRange{ 0xBAu, 0xBAu },
        CodeRange{ 0xC0u, 0xD6u },
        CodeRange{ 0xD8u, 0xF6u },
        CodeRange{ 0xF8u, 0x2C1u },
        CodeRange{ 0x2C6u, 0x2D1u },
        CodeRange{ 0x2E0u, 0x2E4u },
        CodeRange{ 0x2ECu, 0x2ECu },
        CodeRange{ 0x2EEu, 0x2EEu },
        CodeRange{ 0x370u, 0x374u },
        CodeRange{ 0x376u, 0x377u },
        CodeRange{ 0x37Au, 0x37Du },
        CodeRange{ 0x37Fu, 0x37Fu },
        CodeRange{ 0x386u, 0x386u },
        CodeRange{ 0x388u, 0x38Au },
        CodeRange{ 0x38Cu, 0x38Cu },
        CodeRange{ 0x38Eu, 0x3A1u },
        CodeRange{ 0x3A3u, 0x3F5u },
        CodeRange{ 0x3F7u, 0x481u },
        CodeRange{ 0x48Au, 0x52Fu },
        CodeRange{ 0x531u, 0x556u },
        CodeRange{ 0x559u, 0x559u },
        CodeRange{ 0x560u, 0x588u },
        CodeRange{ 0x5D0u, 0x5EAu },
        CodeRange{ 0x5EFu, 0x5F2u },
        CodeRange{ 0x620u, 0x64Au },
        CodeRange{ 0x660u, 0x669u },
        CodeRange{ 0x66Eu, 0x66Fu },
        CodeRange{ 0x671u, 0x6D3u },
        CodeRange{ 0x6D5u, 0x6D5u },
        CodeRange{ 0x6E5u, 0x6E6u },
        CodeRange{ 0x6EEu, 0x6FCu },
        CodeRange{ 0x6FFu, 0x6FFu },
        CodeRange{ 0x710u, 0x710u },
        CodeRange{ 0x712u, 0x72Fu },
        CodeRange{ 0x74Du, 0x7A5u },
        CodeRange{ 0x7B1u, 0x7B1u },
        CodeRange{ 0x7C0u, 0x7EAu },
        CodeRange{ 0x7F4u, 0x7F5u },
        CodeRange{ 0x7FAu, 0x7FAu },
        CodeRange{ 0x800u, 0x815u },
        CodeRange{ 0x81Au, 0x81Au },
        CodeRange{ 0x824u, 0x824u },
        CodeRange{ 0x828u, 0x828u },
        CodeRange{ 0x840u, 0x858u },
        CodeRange{ 0x860u, 0x86Au },
        CodeRange{ 0x870u, 0x887u },
        CodeRange{ 0x889u, 0x88Eu },
        CodeRange{ 0x8A0u, 0x8C9u },
        CodeRange{ 0x904u, 0x939u },
        CodeRange{ 0x93Du, 0x93Du },
        CodeRange{ 0x950u, 0x950u },
        CodeRange{ 0x958u, 0x961u },
        CodeRange{ 0x966u, 0x96Fu },
        CodeRange{ 0x971u, 0x980u },
        CodeRange{ 0x985u, 0x98Cu },
        CodeRange{ 0x98Fu, 0x990u },
        CodeRange{ 0x993u, 0x9A8u },
        CodeRange{ 0x9AAu, 0x9B0u },
        CodeRange{ 0x9B2u, 0x9B2u },
        CodeRange{ 0x9B6u, 0x9B9u },
        CodeRange{ 0x9BDu, 0x9BDu },
        CodeRange{ 0x9CEu, 0x9CEu },
        CodeRange{ 0x9DCu, 0x9DDu },
        CodeRange{ 0x9DFu, 0x9E1u },
        CodeRange{ 0x9E6u, 0x9F1u },
        CodeRange{ 0x9FCu, 0x9FCu },
        CodeRange{ 0xA05u, 0xA0Au },
        CodeRange{ 0xA0Fu, 0xA10u },
        CodeRange{ 0xA13u, 0xA28u },
        CodeRange{ 0xA2Au, 0xA30u },
        CodeRange{ 0xA32u, 0xA33u },
        CodeRange{ 0xA35u, 0xA36u },
        CodeRange{ 0xA38u, 0xA39u },
        CodeRange{ 0xA59u, 0xA5Cu },
        CodeRange{ 0xA5Eu, 0xA5Eu },
        CodeRange{ 0xA66u, 0xA6Fu },
        CodeRange{ 0xA72u, 0xA74u },
        CodeRange{ 0xA85u, 0xA8Du },
        CodeRange{ 0xA8Fu, 0xA91u },
        CodeRange{ 0xA93u, 0xAA8u },
        CodeRange{ 0xAAAu, 0xAB0u },
        CodeRange{ 0xAB2u, 0xAB3u },
        CodeRange{ 0xAB5u, 0xAB9u },
        CodeRange{ 0xABDu, 0xABDu },
        CodeRange{ 0xAD0u, 0xAD0u },
        CodeRange{ 0xAE0u, 0xAE1u },
        CodeRange{ 0xAE6u, 0xAEFu },
        CodeRange{ 0xAF9u, 0xAF9u },
        CodeRange{ 0xB05u, 0xB0Cu },
        CodeRange{ 0xB0Fu, 0xB10u },
        CodeRange{ 0xB13u, 0xB28u },
        CodeRange{ 0xB2Au, 0xB30u },
        CodeRange{ 0xB32u, 0xB33u },
        CodeRange{ 0xB35u, 0xB39u },
        CodeRange{ 0xB3Du, 0xB3Du },
        CodeRange{ 0xB5Cu, 0xB5Du },
        CodeRange{ 0xB5Fu, 0xB61u },
        CodeRange{ 0xB66u, 0xB6Fu },
        CodeRange{ 0xB71u, 0xB71u },
        CodeRange{ 0xB83u, 0xB83u },
        CodeRange{ 0xB85u, 0xB8Au },
        CodeRange{ 0xB8Eu, 0xB90u },
        CodeRange{ 0xB92u, 0xB95u },
        CodeRange{ 0xB99u, 0xB9Au },
        CodeRange{ 0xB9Cu, 0xB9Cu },
        CodeRange{ 0xB9Eu, 0xB9Fu },
        CodeRange{ 0xBA3u, 0xBA4u },
        CodeRange{ 0xBA8u, 0xBAAu },
        CodeRange{ 0xBAEu, 0xBB9u },
        CodeRange{ 0xBD0u, 0xBD0u },
        CodeRange{ 0xBE6u, 0xBEFu },
        CodeRange{ 0xC05u, 0xC0Cu },
        CodeRange{ 0xC0Eu, 0xC10u },
        CodeRange{ 0xC12u, 0xC28u },
        CodeRange{ 0xC2Au, 0xC39u },
        CodeRange{ 0xC3Du, 0xC3Du },
        CodeRange{ 0xC58u, 0xC5Au },
        CodeRange{ 0xC5Du, 0xC5Du },
        CodeRange{ 0xC60u, 0xC61u },
        CodeRange{ 0xC66u, 0xC6Fu },
        CodeRange{ 0xC80u, 0xC80u },
        CodeRange{ 0xC85u, 0xC8Cu },
        CodeRange{ 0xC8Eu, 0xC90u },
        CodeRange{ 0xC92u, 0xCA8u },
        CodeRange{ 0xCAAu, 0xCB3u },
        CodeRange{ 0xCB5u, 0xCB9u },
        CodeRange{ 0xCBDu, 0xCBDu },
        CodeRange{ 0xCDDu, 0xCDEu },
        CodeRange{ 0xCE0u, 0xCE1u },
        CodeRange{ 0xCE6u, 0xCEFu },
        CodeRange{ 0xCF1u, 0xCF2u },
        CodeRange{ 0xD04u, 0xD0Cu },
        CodeRange{ 0xD0Eu, 0xD10u },
        CodeRange{ 0xD12u, 0xD3Au },
        CodeRange{ 0xD3Du, 0xD3Du },
        CodeRange{ 0xD4Eu, 0xD4Eu },
        CodeRange{ 0xD54u, 0xD56u },
        CodeRange{ 0xD5Fu, 0xD61u },
        CodeRange{ 0xD66u, 0xD6Fu },
        CodeRange{ 0xD7Au, 0xD7Fu },
        CodeRange{ 0xD85u, 0xD96u },
        CodeRange{ 0xD9Au, 0xDB1u },
        CodeRange{ 0xDB3u, 0xDBBu },
        CodeRange{ 0xDBDu, 0xDBDu },
        CodeRange{ 0xDC0u, 0xDC6u },
        CodeRange{ 0xDE6u, 0xDEFu },
        CodeRange{ 0xE01u, 0xE30u },
        CodeRange{ 0xE32u, 0xE33u },
        CodeRange{ 0xE40u, 0xE46u },
        CodeRange{ 0xE50u, 0xE59u },
        CodeRange{ 0xE81u, 0xE82u },
        CodeRange{ 0xE84u, 0xE84u },
        CodeRange{ 0xE86u, 0xE8Au },
        CodeRange{ 0xE8Cu, 0xEA3u },
        CodeRange{ 0xEA5u, 0xEA5u },
        CodeRange{ 0xEA7u, 0xEB0u },
        CodeRange{ 0xEB2u, 0xEB3u },
        CodeRange{ 0xEBDu, 0xEBDu },
        CodeRange{ 0xEC0u, 0xEC4u },
        CodeRange{ 0xEC6u, 0xEC6u },
        CodeRange{ 0xED0u, 0xED9u },
        CodeRange{ 0xEDCu, 0xEDFu },
        CodeRange{ 0xF00u, 0xF00u },
        CodeRange{ 0xF20u, 0xF29u },
        CodeRange{ 0xF40u, 0xF47u },
        CodeRange{ 0xF49u, 0xF6Cu },
        CodeRange{ 0xF88u, 0xF8Cu },
        CodeRange{ 0x1000u, 0x102Au },
        CodeRange{ 0x103Fu, 0x1049u },
        CodeRange{ 0x1050u, 0x1055u },
        CodeRange{ 0x105Au, 0x105Du },
        CodeRange{ 0x1061u, 0x1061u },
        CodeRange{ 0x1065u, 0x1066u },
        CodeRange{ 0x106Eu, 0x1070u },
        CodeRange{ 0x1075u, 0x1081u },
        CodeRange{ 0x108Eu, 0x108Eu },
        CodeRange{ 0x1090u, 0x1099u },
        CodeRange{ 0x10A0u, 0x10C5u },
        CodeRange{ 0x10C7u, 0x10C7u },
        CodeRange{ 0x10CDu, 0x10CDu },
        CodeRange{ 0x10D0u, 0x10FAu },
        CodeRange{ 0x10FCu, 0x1248u },
        CodeRange{ 0x124Au, 0x124Du },
        CodeRange{ 0x1250u, 0x1256u },
        CodeRange{ 0x1258u, 0x1258u },
        CodeRange{ 0x125Au, 0x125Du },
        CodeRange{ 0x1260u, 0x1288u },
        CodeRange{ 0x128Au, 0x128Du },
        CodeRange{ 0x1290u, 0x12B0u },
        CodeRange{ 0x12B2u, 0x12B5u },
        CodeRange{ 0x12B8u, 0x12BEu },
        CodeRange{ 0x12C0u, 0x12C0u },
        CodeRange{ 0x12C2u, 0x12C5u },
        CodeRange{ 0x12C8u, 0x12D6u },
        CodeRange{ 0x12D8u, 0x1310u },
        CodeRange{ 0x1312u, 0x1315u },
        CodeRange{ 0x1318u, 0x135Au },
        CodeRange{ 0x1380u, 0x138Fu },
        CodeRange{ 0x13A0u, 0x13F5u },
        CodeRange{ 0x13F8u, 0x13FDu },
        CodeRange{ 0x1401u, 0x166Cu },
        CodeRange{ 0x166Fu, 0x167Fu },
        CodeRange{ 0x1681u, 0x169Au },
        CodeRange{ 0x16A0u, 0x16EAu },
        CodeRange{ 0x16F1u, 0x16F8u },
        CodeRange{ 0x1700u, 0x1711u },
        CodeRange{ 0x171Fu, 0x1731u },
        CodeRange{ 0x1740u, 0x1751u },
        CodeRange{ 0x1760u, 0x176Cu },
        CodeRange{ 0x176Eu, 0x1770u },
        CodeRange{ 0x1780u, 0x17B3u },
        CodeRange{ 0x17D7u, 0x17D7u },
        CodeRange{ 0x17DCu, 0x17DCu },
        CodeRange{ 0x17E0u, 0x17E9u },
        CodeRange{ 0x1810u, 0x1819u },
        CodeRange{ 0x1820u, 0x1878u },
        CodeRange{ 0x1880u, 0x1884u },
        CodeRange{ 0x1887u, 0x18A8u },
        CodeRange{ 0x18AAu, 0x18AAu },
        CodeRange{ 0x18B0u, 0x18F5u },
        CodeRange{ 0x1900u, 0x191Eu },
        CodeRange{ 0x1946u, 0x196Du },
        CodeRange{ 0x1970u, 0x1974u },
        CodeRange{ 0x1980u, 0x19ABu },
        CodeRange{ 0x19B0u, 0x19C9u },
        CodeRange{ 0x19D0u, 0x19D9u },
        CodeRange{ 0x1A00u, 0x1A16u },
        CodeRange{ 0x1A20u, 0x1A54u },
        CodeRange{ 0x1A80u, 0x1A89u },
        CodeRange{ 0x1A90u, 0x1A99u },
        CodeRange{ 0x1AA7u, 0x1AA7u },
        CodeRange{ 0x1B05u, 0x1B33u },
        CodeRange{ 0x1B45u, 0x1B4Cu },
        CodeRange{ 0x1B50u, 0x1B59u },
        CodeRange{ 0x1B83u, 0x1BA0u },
        CodeRange{ 0x1BAEu, 0x1BE5u },
        CodeRange{ 0x1C00u, 0x1C23u },
        CodeRange{ 0x1C40u, 0x1C49u },
        CodeRange{ 0x1C4Du, 0x1C7Du },
        CodeRange{ 0x1C80u, 0x1C8Au },
        CodeRange{ 0x1C90u, 0x1CBAu },
        CodeRange{ 0x1CBDu, 0x1CBFu },
        CodeRange{ 0x1CE9u, 0x1CECu },
        CodeRange{ 0x1CEEu, 0x1CF3u },
        CodeRange{ 0x1CF5u, 0x1CF6u },
        CodeRange{ 0x1CFAu, 0x1CFAu },
        CodeRange{ 0x1D00u, 0x1DBFu },
        CodeRange{ 0x1E00u, 0x1F15u },
        CodeRange{ 0x1F18u, 0x1F1Du },
        CodeRange{ 0x1F20u, 0x1F45u },
        CodeRange{ 0x1F48u, 0x1F4Du },
        CodeRange{ 0x1F50u, 0x1F57u },
        CodeRange{ 0x1F59u, 0x1F59u },
        CodeRange{ 0x1F5Bu, 0x1F5Bu },
        CodeRange{ 0x1F5Du, 0x1F5Du },
        CodeRange{ 0x1F5Fu, 0x1F7Du },
        CodeRange{ 0x1F80u, 0x1FB4u },
        CodeRange{ 0x1FB6u, 0x1FBCu },
        CodeRange{ 0x1FBEu, 0x1FBEu },
        CodeRange{ 0x1FC2u, 0x1FC4u },
        CodeRange{ 0x1FC6u, 0x1FCCu },
        CodeRange{ 0x1FD0u, 0x1FD3u },
        CodeRange{ 0x1FD6u, 0x1FDBu },
        CodeRange{ 0x1FE0u, 0x1FECu },
        CodeRange{ 0x1FF2u, 0x1FF4u },
        CodeRange{ 0x1FF6u, 0x1FFCu },
        CodeRange{ 0x2071u, 0x2071u },
        CodeRange{ 0x207Fu, 0x207Fu },
        CodeRange{ 0x2090u, 0x209Cu },
        CodeRange{ 0x2102u, 0x2102u },
        CodeRange{ 0x2107u, 0x2107u },
        CodeRange{ 0x210Au, 0x2113u },
        CodeRange{ 0x2115u, 0x2115u },
        CodeRange{ 0x2119u, 0x211Du },
        CodeRange{ 0x2124u, 0x2124u },
        CodeRange{ 0x2126u, 0x2126u },
        CodeRange{ 0x2128u, 0x2128u },
        CodeRange{ 0x212Au, 0x212Du },
        CodeRange{ 0x212Fu, 0x2139u },
        CodeRange{ 0x213Cu, 0x213Fu },
        CodeRange{ 0x2145u, 0x2149u },
        CodeRange{ 0x214Eu, 0x214Eu },
        CodeRange{ 0x2183u, 0x2184u },
        CodeRange{ 0x2C00u, 0x2CE4u },
        CodeRange{ 0x2CEBu, 0x2CEEu },
        CodeRange{ 0x2CF2u, 0x2CF3u },
        CodeRange{ 0x2D00u, 0x2D25u },
        CodeRange{ 0x2D27u, 0x2D27u },
        CodeRange{ 0x2D2Du, 0x2D2Du },
        CodeRange{ 0x2D30u, 0x2D67u },
        CodeRange{ 0x2D6Fu, 0x2D6Fu },
        CodeRange{ 0x2D80u, 0x2D96u },
        CodeRange{ 0x2DA0u, 0x2DA6u },
        CodeRange{ 0x2DA8u, 0x2DAEu },
        CodeRange{ 0x2DB0u, 0x2DB6u },
        CodeRange{ 0x2DB8u, 0x2DBEu },
        CodeRange{ 0x2DC0u, 0x2DC6u },
        CodeRange{ 0x2DC8u, 0x2DCEu },
        CodeRange{ 0x2DD0u, 0x2DD6u },
        CodeRange{ 0x2DD8u, 0x2DDEu },
        CodeRange{ 0x2E2Fu, 0x2E2Fu },
        CodeRange{ 0x3005u, 0x3006u },
        CodeRange{ 0x3031u, 0x3035u },
        CodeRange{ 0x303Bu, 0x303Cu },
        CodeRange{ 0x3041u, 0x3096u },
        CodeRange{ 0x309Du, 0x309Fu },
        CodeRange{ 0x30A1u, 0x30FAu },
        CodeRange{ 0x30FCu, 0x30FFu },
        CodeRange{ 0x3105u, 0x312Fu },
        CodeRange{ 0x3131u, 0x318Eu },
        CodeRange{ 0x31A0u, 0x31BFu },
        CodeRange{ 0x31F0u, 0x31FFu },
        CodeRange{ 0x3400u, 0x4DBFu },
        CodeRange{ 0x4E00u, 0xA48Cu },
        CodeRange{ 0xA4D0u, 0xA4FDu },
        CodeRange{ 0xA500u, 0xA60Cu },
        CodeRange{ 0xA610u, 0xA62Bu },
        CodeRange{ 0xA640u, 0xA66Eu },
        CodeRange{ 0xA67Fu, 0xA69Du },
        CodeRange{ 0xA6A0u, 0xA6E5u },
        CodeRange{ 0xA717u, 0xA71Fu },
        CodeRange{ 0xA722u, 0xA788u },
        CodeRange{ 0xA78Bu, 0xA7CDu },
        CodeRange{ 0xA7D0u, 0xA7D1u },
        CodeRange{ 0xA7D3u, 0xA7D3u },
        CodeRange{ 0xA7D5u, 0xA7DCu },
        CodeRange{ 0xA7F2u, 0xA801u },
        CodeRange{ 0xA803u, 0xA805u },
        CodeRange{ 0xA807u, 0xA80Au },
        CodeRange{ 0xA80Cu, 0xA822u },
        CodeRange{ 0xA840u, 0xA873u },
        CodeRange{ 0xA882u, 0xA8B3u },
        CodeRange{ 0xA8D0u, 0xA8D9u },
        CodeRange{ 0xA8F2u, 0xA8F7u },
        CodeRange{ 0xA8FBu, 0xA8FBu },
        CodeRange{ 0xA8FDu, 0xA8FEu },
        CodeRange{ 0xA900u, 0xA925u },
        CodeRange{ 0xA930u, 0xA946u },
        CodeRange{ 0xA960u, 0xA97Cu },
        CodeRange{ 0xA984u, 0xA9B2u },
        CodeRange{ 0xA9CFu, 0xA9D9u },
        CodeRange{ 0xA9E0u, 0xA9E4u },
        CodeRange{ 0xA9E6u, 0xA9FEu },
        CodeRange{ 0xAA00u, 0xAA28u },
        CodeRange{ 0xAA40u, 0xAA42u },
        CodeRange{ 0xAA44u, 0xAA4Bu },
        CodeRange{ 0xAA50u, 0xAA59u },
        CodeRange{ 0xAA60u, 0xAA76u },
        CodeRange{ 0xAA7Au, 0xAA7Au },
        CodeRange{ 0xAA7Eu, 0xAAAFu },
        CodeRange{ 0xAAB1u, 0xAAB1u },
        CodeRange{ 0xAAB5u, 0xAAB6u },
        CodeRange{ 0xAAB9u, 0xAABDu },
        CodeRange{ 0xAAC0u, 0xAAC0u },
        CodeRange{ 0xAAC2u, 0xAAC2u },
        CodeRange{ 0xAADBu, 0xAADDu },
        CodeRange{ 0xAAE0u, 0xAAEAu },
        CodeRange{ 0xAAF2u, 0xAAF4u },
        CodeRange{ 0xAB01u, 0xAB06u },
        CodeRange{ 0xAB09u, 0xAB0Eu },
        CodeRange{ 0xAB11u, 0xAB16u },
        CodeRange{ 0xAB20u, 0xAB26u },
        CodeRange{ 0xAB28u, 0xAB2Eu },
        CodeRange{ 0xAB30u, 0xAB5Au },
        CodeRange{ 0xAB5Cu, 0xAB69u },
        CodeRange{ 0xAB70u, 0xABE2u },
        CodeRange{ 0xABF0u, 0xABF9u },
        CodeRange{ 0xAC00u, 0xD7A3u },
        CodeRange{ 0xD7B0u, 0xD7C6u },
        CodeRange{ 0xD7CBu, 0xD7FBu },
        CodeRange{ 0xF900u, 0xFA6Du },
        CodeRange{ 0xFA70u, 0xFAD9u },
        CodeRange{ 0xFB00u, 0xFB06u },
        CodeRange{ 0xFB13u, 0xFB17u },
        CodeRange{ 0xFB1Du, 0xFB1Du },
        CodeRange{ 0xFB1Fu, 0xFB28u },
        CodeRange{ 0xFB2Au, 0xFB36u },
        CodeRange{ 0xFB38u, 0xFB3Cu },
        CodeRange{ 0xFB3Eu, 0xFB3Eu },
        CodeRange{ 0xFB40u, 0xFB41u },
        CodeRange{ 0xFB43u, 0xFB44u },
        CodeRange{ 0xFB46u, 0xFBB1u },
        CodeRange{ 0xFBD3u, 0xFD3Du },
        CodeRange{ 0xFD50u, 0xFD8Fu },
        CodeRange{ 0xFD92u, 0xFDC7u },
        CodeRange{ 0xFDF0u, 0xFDFBu },
        CodeRange{ 0xFE70u, 0xFE74u },
        CodeRange{ 0xFE76u, 0xFEFCu },
        CodeRange{ 0xFF10u, 0xFF19u },
        CodeRange{ 0xFF21u, 0xFF3Au },
        CodeRange{ 0xFF41u, 0xFF5Au },
        CodeRange{ 0xFF66u, 0xFFBEu },
        CodeRange{ 0xFFC2u, 0xFFC7u },
        CodeRange{ 0xFFCAu, 0xFFCFu },
        CodeRange{ 0xFFD2u, 0xFFD7u },
        CodeRange{ 0xFFDAu, 0xFFDCu },
    };

    constexpr auto TextStatsStopWords = std::to_array<std::wstring_view>({
        L"the",L"a",L"an",L"and",L"or",L"but",L"if",L"of",L"to",L"in",L"on",L"at",L"by",L"for",L"with",L"as",L"is",
        L"are",L"was",L"were",L"be",L"been",L"being",L"it",L"its",L"this",L"that",L"these",L"those",L"i",L"you",
        L"he",L"she",L"they",L"we",L"me",L"him",L"her",L"them",L"us",L"my",L"your",L"his",L"their",L"our",L"not",
        L"no",L"do",L"does",L"did",L"so",L"than",L"then",L"too",L"very",L"can",L"will",L"just",L"from",L"up",L"out",
        L"about",L"into",L"over",L"after",L"under",L"again",L"once",L"here",L"there",L"when",L"where",L"why",L"how",
        L"all",L"any",L"both",L"each",L"few",L"more",L"most",L"other",L"some",L"such",L"only",L"own",L"same"
    });

    constexpr auto FrequencyStopWords = std::to_array<std::wstring_view>({
        L"a",L"an",L"and",L"are",L"as",L"at",L"be",L"been",L"but",L"by",L"for",L"from",L"had",L"has",
        L"have",L"he",L"her",L"him",L"his",L"i",L"if",L"in",L"into",L"is",L"it",L"its",L"me",L"my",L"no",
        L"not",L"of",L"on",L"or",L"our",L"she",L"so",L"that",L"the",L"their",L"them",L"then",L"there",
        L"these",L"they",L"this",L"to",L"was",L"we",L"were",L"what",L"when",L"which",L"who",L"will",
        L"with",L"you",L"your",L"would",L"could",L"should",L"been",L"being",L"do",L"does",L"did",
        L"just",L"than",L"too",L"very",L"can",L"us",L"am"
    });

    [[nodiscard]] constexpr bool IsManagedWhitespace(std::uint32_t value) noexcept
    {
        return (value >= 0x0009u && value <= 0x000Du) ||
            value == 0x0020u || value == 0x0085u || value == 0x00A0u ||
            value == 0x1680u || (value >= 0x2000u && value <= 0x200Au) ||
            value == 0x2028u || value == 0x2029u || value == 0x202Fu ||
            value == 0x205Fu || value == 0x3000u;
    }

    [[nodiscard]] constexpr bool IsHighSurrogate(std::uint32_t value) noexcept
    {
        return value >= 0xD800u && value <= 0xDBFFu;
    }

    [[nodiscard]] constexpr bool IsLowSurrogate(std::uint32_t value) noexcept
    {
        return value >= 0xDC00u && value <= 0xDFFFu;
    }

    [[nodiscard]] bool IsLetterOrDigit(wchar_t value) noexcept
    {
        auto const code = static_cast<std::uint32_t>(static_cast<std::uint16_t>(value));
        auto found = std::upper_bound(
            LetterOrDigitRanges.begin(),
            LetterOrDigitRanges.end(),
            code,
            [](std::uint32_t target, CodeRange const& range) { return target < range.first; });
        if (found == LetterOrDigitRanges.begin()) return false;
        --found;
        return code <= found->last;
    }

    [[nodiscard]] bool IsCjk(wchar_t value) noexcept
    {
        auto const code = static_cast<std::uint32_t>(static_cast<std::uint16_t>(value));
        return (code >= 0x4E00u && code <= 0x9FFFu) ||
            (code >= 0x3400u && code <= 0x4DBFu) ||
            (code >= 0x3040u && code <= 0x30FFu) ||
            (code >= 0xF900u && code <= 0xFAFFu);
    }

    [[nodiscard]] std::uint32_t LowerInvariant(std::uint32_t codePoint) noexcept
    {
        for (auto const& range : LowerRanges)
        {
            if (codePoint >= range.first && codePoint <= range.last &&
                (codePoint - range.first) % range.step == 0)
            {
                return static_cast<std::uint32_t>(
                    static_cast<std::int64_t>(codePoint) + range.delta);
            }
        }
        auto const found = std::lower_bound(
            LowerPairs.begin(), LowerPairs.end(), codePoint,
            [](LowerPair const& pair, std::uint32_t value) { return pair.from < value; });
        return found != LowerPairs.end() && found->from == codePoint ? found->to : codePoint;
    }

    void AppendScalar(std::wstring& output, std::uint32_t codePoint)
    {
        if constexpr (sizeof(wchar_t) == 2)
        {
            if (codePoint > 0xFFFFu)
            {
                codePoint -= 0x10000u;
                output.push_back(static_cast<wchar_t>(0xD800u + (codePoint >> 10)));
                output.push_back(static_cast<wchar_t>(0xDC00u + (codePoint & 0x3FFu)));
            }
            else
            {
                output.push_back(static_cast<wchar_t>(codePoint));
            }
        }
        else
        {
            output.push_back(static_cast<wchar_t>(codePoint));
        }
    }

    [[nodiscard]] std::uint32_t DecodeValidScalar(
        std::wstring_view input,
        std::size_t& index) noexcept
    {
        auto value = static_cast<std::uint32_t>(input[index]);
        if constexpr (sizeof(wchar_t) == 2)
        {
            if (IsHighSurrogate(value) && index + 1 < input.size())
            {
                auto const low = static_cast<std::uint32_t>(input[index + 1]);
                if (IsLowSurrogate(low))
                {
                    ++index;
                    return 0x10000u + ((value - 0xD800u) << 10) + (low - 0xDC00u);
                }
            }
        }
        return value;
    }

    [[nodiscard]] std::wstring ToLowerInvariant(std::wstring_view input)
    {
        std::wstring output;
        output.reserve(input.size());
        for (std::size_t index{}; index < input.size(); ++index)
        {
            AppendScalar(output, LowerInvariant(DecodeValidScalar(input, index)));
        }
        return output;
    }

    [[nodiscard]] std::wstring FoldOrdinalIgnoreCase(std::wstring_view input)
    {
        return winforge::core::textdiff::FoldOrdinalIgnoreCase(input);
    }

    [[nodiscard]] int CompareFoldedOrdinal(
        std::wstring_view left,
        std::wstring_view right) noexcept
    {
        auto const common = (std::min)(left.size(), right.size());
        std::size_t index{};
        while (index < common)
        {
            auto const leftPair = IsHighSurrogate(left[index]) &&
                index + 1 < left.size() && IsLowSurrogate(left[index + 1]);
            auto const rightPair = IsHighSurrogate(right[index]) &&
                index + 1 < right.size() && IsLowSurrogate(right[index + 1]);
            if (!leftPair)
            {
                if (rightPair) return -1;
                auto const l = static_cast<std::uint16_t>(left[index]);
                auto const r = static_cast<std::uint16_t>(right[index]);
                if (l != r) return l < r ? -1 : 1;
                ++index;
                continue;
            }
            if (!rightPair) return 1;
            auto const l = 0x10000u +
                ((static_cast<std::uint32_t>(left[index]) - 0xD800u) << 10) +
                (static_cast<std::uint32_t>(left[index + 1]) - 0xDC00u);
            auto const r = 0x10000u +
                ((static_cast<std::uint32_t>(right[index]) - 0xD800u) << 10) +
                (static_cast<std::uint32_t>(right[index + 1]) - 0xDC00u);
            if (l != r) return l < r ? -1 : 1;
            index += 2;
        }
        if (left.size() == right.size()) return 0;
        return left.size() < right.size() ? -1 : 1;
    }

    [[nodiscard]] int CompareOrdinalIgnoreCase(
        std::wstring_view left,
        std::wstring_view right)
    {
        auto const foldedLeft = FoldOrdinalIgnoreCase(left);
        auto const foldedRight = FoldOrdinalIgnoreCase(right);
        return CompareFoldedOrdinal(foldedLeft, foldedRight);
    }

    struct IcuCollator
    {
        UCollator* value{};
        std::mutex mutex;

        IcuCollator() noexcept
        {
            wchar_t localeName[LOCALE_NAME_MAX_LENGTH]{};
            if (GetUserDefaultLocaleName(localeName, LOCALE_NAME_MAX_LENGTH) == 0) return;
            char locale[LOCALE_NAME_MAX_LENGTH]{};
            std::size_t index{};
            for (; index + 1 < std::size(locale) && localeName[index] != L'\0'; ++index)
            {
                if (localeName[index] > 0x7F) return;
                locale[index] = static_cast<char>(localeName[index]);
            }
            locale[index] = '\0';
            UErrorCode status = U_ZERO_ERROR;
            value = ucol_open(locale, &status);
            if (U_FAILURE(status))
            {
                if (value) ucol_close(value);
                value = nullptr;
                return;
            }
            ucol_setStrength(value, UCOL_SECONDARY);
        }

        ~IcuCollator()
        {
            if (value) ucol_close(value);
        }

        IcuCollator(IcuCollator const&) = delete;
        IcuCollator& operator=(IcuCollator const&) = delete;
    };

    [[nodiscard]] int CompareCurrentCultureIgnoreCase(
        std::wstring_view left,
        std::wstring_view right) noexcept
    {
        static IcuCollator collator;
        if (collator.value)
        {
            static_assert(sizeof(wchar_t) == sizeof(UChar));
            std::scoped_lock guard(collator.mutex);
            auto const result = ucol_strcoll(
                collator.value,
                reinterpret_cast<UChar const*>(left.data()), static_cast<std::int32_t>(left.size()),
                reinterpret_cast<UChar const*>(right.data()), static_cast<std::int32_t>(right.size()));
            if (result == UCOL_LESS) return -1;
            if (result == UCOL_GREATER) return 1;
            return 0;
        }
        try { return CompareOrdinalIgnoreCase(left, right); }
        catch (...) { return 0; }
    }

    template<std::size_t Size>
    [[nodiscard]] std::unordered_set<std::wstring> BuildFoldedStopWords(
        std::array<std::wstring_view, Size> const& words)
    {
        std::unordered_set<std::wstring> result;
        result.reserve(words.size());
        for (auto const word : words) result.insert(FoldOrdinalIgnoreCase(word));
        return result;
    }

    [[nodiscard]] std::unordered_set<std::wstring> const& TextStatsStopWordSet()
    {
        static auto const words = BuildFoldedStopWords(TextStatsStopWords);
        return words;
    }

    [[nodiscard]] std::unordered_set<std::wstring> const& FrequencyStopWordSet()
    {
        static auto const words = BuildFoldedStopWords(FrequencyStopWords);
        return words;
    }

    [[nodiscard]] bool HasNonWhitespace(std::wstring_view text) noexcept
    {
        for (auto const value : text)
        {
            if (!IsManagedWhitespace(static_cast<std::uint16_t>(value))) return true;
        }
        return false;
    }

    [[nodiscard]] std::vector<std::wstring> TokenizeTextStats(std::wstring_view text)
    {
        std::vector<std::wstring> words;
        std::wstring current;
        for (auto const value : text)
        {
            if (IsCjk(value))
            {
                if (!current.empty())
                {
                    words.push_back(std::move(current));
                    current.clear();
                }
                words.emplace_back(1, value);
            }
            else if (IsLetterOrDigit(value) || value == L'\'' || value == L'\u2019')
            {
                current.push_back(value);
            }
            else if (!current.empty())
            {
                words.push_back(std::move(current));
                current.clear();
            }
        }
        if (!current.empty()) words.push_back(std::move(current));
        return words;
    }

    [[nodiscard]] int CountSentences(std::wstring_view text) noexcept
    {
        int count{};
        bool inRun{};
        for (auto const value : text)
        {
            auto const terminal = value == L'.' || value == L'!' || value == L'?' ||
                value == L'\u3002' || value == L'\uFF01' || value == L'\uFF1F';
            if (terminal)
            {
                if (!inRun) { ++count; inRun = true; }
            }
            else if (!IsManagedWhitespace(static_cast<std::uint16_t>(value)))
            {
                inRun = false;
            }
        }
        return count;
    }

    [[nodiscard]] int CountParagraphs(std::wstring_view text)
    {
        std::wstring normalized;
        normalized.reserve(text.size());
        for (std::size_t index{}; index < text.size(); ++index)
        {
            if (text[index] == L'\r')
            {
                if (index + 1 < text.size() && text[index + 1] == L'\n') ++index;
                normalized.push_back(L'\n');
            }
            else
            {
                normalized.push_back(text[index]);
            }
        }

        int count{};
        std::size_t start{};
        while (true)
        {
            auto const delimiter = normalized.find(L"\n\n", start);
            auto const block = delimiter == std::wstring::npos
                ? std::wstring_view(normalized).substr(start)
                : std::wstring_view(normalized).substr(start, delimiter - start);
            if (HasNonWhitespace(block)) ++count;
            if (delimiter == std::wstring::npos) break;
            start = delimiter + 2;
        }
        return count;
    }

    [[nodiscard]] int SyllablesIn(std::wstring_view word)
    {
        if (word.empty()) return 0;
        if (word.size() == 1 && IsCjk(word.front())) return 1;
        auto const lowered = ToLowerInvariant(word);
        std::wstring letters;
        for (auto const value : lowered)
        {
            if (value >= L'a' && value <= L'z') letters.push_back(value);
        }
        if (letters.empty()) return 1;

        int count{};
        bool previousVowel{};
        for (auto const value : letters)
        {
            auto const vowel = value == L'a' || value == L'e' || value == L'i' ||
                value == L'o' || value == L'u' || value == L'y';
            if (vowel && !previousVowel) ++count;
            previousVowel = vowel;
        }
        if (letters.back() == L'e' && count > 1) --count;
        return (std::max)(1, count);
    }

    [[nodiscard]] double RoundToEven(double value, int digits) noexcept
    {
        static constexpr std::array<double, 2> powers{ 1.0, 10.0 };
        auto const scale = powers[static_cast<std::size_t>((std::clamp)(digits, 0, 1))];
        return std::nearbyint(value * scale) / scale;
    }

    struct CountedTerm
    {
        std::wstring term;
        std::wstring folded;
        int count{};
    };

    void AddOrdinalCount(
        std::vector<CountedTerm>& counts,
        std::unordered_map<std::wstring, std::size_t>& indices,
        std::wstring const& term)
    {
        auto const [found, inserted] = indices.try_emplace(term, counts.size());
        if (!inserted)
        {
            ++counts[found->second].count;
            return;
        }
        counts.push_back({ term, {}, 1 });
    }

    void AddOrdinalIgnoreCaseCount(
        std::vector<CountedTerm>& counts,
        std::unordered_map<std::wstring, std::size_t>& indices,
        std::wstring const& term,
        std::wstring const& folded)
    {
        auto const [found, inserted] = indices.try_emplace(folded, counts.size());
        if (!inserted)
        {
            ++counts[found->second].count;
            return;
        }
        counts.push_back({ term, folded, 1 });
    }

    [[nodiscard]] std::wstring TrimApostropheHyphen(std::wstring value)
    {
        auto first = std::size_t{};
        while (first < value.size() && (value[first] == L'\'' || value[first] == L'-')) ++first;
        auto last = value.size();
        while (last > first && (value[last - 1] == L'\'' || value[last - 1] == L'-')) --last;
        return value.substr(first, last - first);
    }

    [[nodiscard]] std::vector<std::wstring> TokenizeFrequency(
        std::wstring_view text,
        bool stripPunctuation)
    {
        std::vector<std::wstring> tokens;
        if (!stripPunctuation)
        {
            std::size_t start{};
            while (start < text.size())
            {
                while (start < text.size() &&
                    IsManagedWhitespace(static_cast<std::uint16_t>(text[start]))) ++start;
                auto end = start;
                while (end < text.size() &&
                    !IsManagedWhitespace(static_cast<std::uint16_t>(text[end]))) ++end;
                if (end > start) tokens.emplace_back(text.substr(start, end - start));
                start = end;
            }
            return tokens;
        }

        std::wstring current;
        for (auto const value : text)
        {
            if (IsLetterOrDigit(value) || value == L'\'' || value == L'-')
            {
                current.push_back(value);
            }
            else if (!current.empty())
            {
                tokens.push_back(TrimApostropheHyphen(std::move(current)));
                current.clear();
            }
        }
        if (!current.empty()) tokens.push_back(TrimApostropheHyphen(std::move(current)));
        return tokens;
    }

    [[nodiscard]] std::vector<std::wstring> FrequencyWords(
        std::wstring_view text,
        WordFrequencyOptions const& options)
    {
        std::vector<std::wstring> words;
        auto const minimum = (std::max)(1, options.minLength);
        auto const* stopWords = options.removeStopWords ? &FrequencyStopWordSet() : nullptr;
        for (auto raw : TokenizeFrequency(text, options.stripPunctuation))
        {
            if (options.caseInsensitive) raw = ToLowerInvariant(raw);
            if (static_cast<int>(raw.size()) < minimum) continue;
            if (stopWords)
            {
                auto const folded = FoldOrdinalIgnoreCase(raw);
                if (stopWords->contains(folded)) continue;
            }
            words.push_back(std::move(raw));
        }
        return words;
    }

    [[nodiscard]] std::vector<std::wstring> FrequencyCharacters(
        std::wstring_view text,
        bool caseInsensitive)
    {
        std::vector<std::wstring> characters;
        for (std::size_t index{}; index < text.size(); ++index)
        {
            auto value = static_cast<std::uint32_t>(text[index]);
            if constexpr (sizeof(wchar_t) == 2)
            {
                if (IsHighSurrogate(value) && index + 1 < text.size() &&
                    IsLowSurrogate(static_cast<std::uint32_t>(text[index + 1])))
                {
                    auto const low = static_cast<std::uint32_t>(text[++index]);
                    value = 0x10000u + ((value - 0xD800u) << 10) + (low - 0xDC00u);
                }
                else if (IsHighSurrogate(value) || IsLowSurrogate(value))
                {
                    value = 0xFFFDu;
                }
            }
            if (IsManagedWhitespace(value)) continue;
            if (caseInsensitive) value = LowerInvariant(value);
            std::wstring scalar;
            AppendScalar(scalar, value);
            characters.push_back(std::move(scalar));
        }
        return characters;
    }

    [[nodiscard]] std::wstring FormatOneDecimal(double value)
    {
        // The managed custom numeric format "0.0" rounds midpoint values away
        // from zero. Percentages are bounded to 0..100, so integer tenths are
        // both exact and independent of the process C locale.
        auto const tenths = static_cast<int>(std::round(value * 10.0));
        return std::to_wstring(tenths / 10) + L"." +
            std::to_wstring((std::abs)(tenths % 10));
    }

    [[nodiscard]] std::wstring EscapeCsv(std::wstring_view value)
    {
        std::wstring escaped;
        escaped.reserve(value.size() + 2);
        escaped.push_back(L'"');
        for (auto const ch : value)
        {
            if (ch == L'"') escaped.push_back(L'"');
            escaped.push_back(ch);
        }
        escaped.push_back(L'"');
        return escaped;
    }

    [[nodiscard]] std::wstring NormalizeComparison(
        std::wstring_view input,
        bool ignoreCase,
        bool ignoreWhitespace)
    {
        std::wstring normalized;
        normalized.reserve(input.size());
        for (auto const value : input)
        {
            if (!ignoreWhitespace ||
                !IsManagedWhitespace(static_cast<std::uint16_t>(value)))
            {
                normalized.push_back(value);
            }
        }
        return ignoreCase ? ToLowerInvariant(normalized) : normalized;
    }

    [[nodiscard]] int Levenshtein(std::wstring_view a, std::wstring_view b)
    {
        if (a.empty()) return static_cast<int>(b.size());
        if (b.empty()) return static_cast<int>(a.size());
        std::vector<int> previous(b.size() + 1);
        std::vector<int> current(b.size() + 1);
        for (std::size_t j{}; j <= b.size(); ++j) previous[j] = static_cast<int>(j);
        for (std::size_t i = 1; i <= a.size(); ++i)
        {
            current[0] = static_cast<int>(i);
            for (std::size_t j = 1; j <= b.size(); ++j)
            {
                auto const cost = a[i - 1] == b[j - 1] ? 0 : 1;
                current[j] = (std::min)({ current[j - 1] + 1,
                    previous[j] + 1, previous[j - 1] + cost });
            }
            std::swap(previous, current);
        }
        return previous[b.size()];
    }

    [[nodiscard]] int DamerauLevenshtein(std::wstring_view a, std::wstring_view b)
    {
        auto const la = a.size();
        auto const lb = b.size();
        if (la == 0) return static_cast<int>(lb);
        if (lb == 0) return static_cast<int>(la);
        std::vector<int> distances((la + 1) * (lb + 1));
        auto cell = [&](std::size_t i, std::size_t j) -> int&
        {
            return distances[i * (lb + 1) + j];
        };
        for (std::size_t i{}; i <= la; ++i) cell(i, 0) = static_cast<int>(i);
        for (std::size_t j{}; j <= lb; ++j) cell(0, j) = static_cast<int>(j);
        for (std::size_t i = 1; i <= la; ++i)
        {
            for (std::size_t j = 1; j <= lb; ++j)
            {
                auto const cost = a[i - 1] == b[j - 1] ? 0 : 1;
                auto value = (std::min)({ cell(i - 1, j) + 1,
                    cell(i, j - 1) + 1, cell(i - 1, j - 1) + cost });
                if (i > 1 && j > 1 && a[i - 1] == b[j - 2] && a[i - 2] == b[j - 1])
                {
                    value = (std::min)(value, cell(i - 2, j - 2) + 1);
                }
                cell(i, j) = value;
            }
        }
        return cell(la, lb);
    }

    [[nodiscard]] int Hamming(std::wstring_view a, std::wstring_view b) noexcept
    {
        int distance{};
        for (std::size_t index{}; index < a.size(); ++index)
        {
            if (a[index] != b[index]) ++distance;
        }
        return distance;
    }

    [[nodiscard]] double Jaro(std::wstring_view a, std::wstring_view b)
    {
        if (a.empty() && b.empty()) return 1.0;
        if (a.empty() || b.empty()) return 0.0;

        struct OrderedPositions
        {
            std::vector<int> values;
            std::vector<std::size_t> successor;

            [[nodiscard]] std::size_t Find(std::size_t index) noexcept
            {
                auto root = index;
                while (successor[root] != root) root = successor[root];
                while (successor[index] != index)
                {
                    auto const next = successor[index];
                    successor[index] = root;
                    index = next;
                }
                return root;
            }

            void Remove(std::size_t index) noexcept
            {
                successor[index] = Find(index + 1);
            }
        };

        auto matchDistance = static_cast<int>((std::max)(a.size(), b.size()) / 2) - 1;
        if (matchDistance < 0) matchDistance = 0;
        std::vector<bool> aMatched(a.size());
        std::vector<bool> bMatched(b.size());

        // The managed oracle greedily chooses the first still-unmatched equal
        // code unit in each window. Per-code-unit ordered positions plus a
        // successor set reproduce that exact choice without rescanning a
        // potentially O(n)-wide window for every character.
        std::unordered_map<wchar_t, OrderedPositions> positions;
        positions.reserve((std::min)(b.size(), std::size_t{ 65'536 }));
        for (std::size_t index{}; index < b.size(); ++index)
        {
            positions[b[index]].values.push_back(static_cast<int>(index));
        }
        for (auto& [character, bucket] : positions)
        {
            (void)character;
            bucket.successor.resize(bucket.values.size() + 1);
            for (std::size_t index{}; index < bucket.successor.size(); ++index)
            {
                bucket.successor[index] = index;
            }
        }

        int matches{};
        for (std::size_t i{}; i < a.size(); ++i)
        {
            auto const start = (std::max)(0, static_cast<int>(i) - matchDistance);
            auto const end = (std::min)(static_cast<int>(b.size()),
                static_cast<int>(i) + matchDistance + 1);
            auto bucket = positions.find(a[i]);
            if (bucket == positions.end()) continue;
            auto& ordered = bucket->second;
            auto const lower = std::lower_bound(ordered.values.begin(), ordered.values.end(), start);
            auto positionIndex = ordered.Find(
                static_cast<std::size_t>(lower - ordered.values.begin()));
            if (positionIndex == ordered.values.size() || ordered.values[positionIndex] >= end) continue;
            auto const position = static_cast<std::size_t>(ordered.values[positionIndex]);
            ordered.Remove(positionIndex);
            aMatched[i] = true;
            bMatched[position] = true;
            ++matches;
        }
        if (matches == 0) return 0.0;
        double transpositions{};
        std::size_t k{};
        for (std::size_t i{}; i < a.size(); ++i)
        {
            if (!aMatched[i]) continue;
            while (!bMatched[k]) ++k;
            if (a[i] != b[k]) ++transpositions;
            ++k;
        }
        transpositions /= 2.0;
        auto const m = static_cast<double>(matches);
        return (m / static_cast<double>(a.size()) +
            m / static_cast<double>(b.size()) +
            (m - transpositions) / m) / 3.0;
    }

    [[nodiscard]] double JaroWinkler(std::wstring_view a, std::wstring_view b)
    {
        auto const jaro = Jaro(a, b);
        int prefix{};
        auto const maximum = (std::min)(std::size_t{ 4 }, (std::min)(a.size(), b.size()));
        for (std::size_t index{}; index < maximum && a[index] == b[index]; ++index) ++prefix;
        return jaro + static_cast<double>(prefix) * 0.1 * (1.0 - jaro);
    }

    [[nodiscard]] int LongestCommonSubstring(std::wstring_view a, std::wstring_view b)
    {
        if (a.empty() || b.empty()) return 0;
        std::vector<int> previous(b.size() + 1);
        std::vector<int> current(b.size() + 1);
        int best{};
        for (std::size_t i = 1; i <= a.size(); ++i)
        {
            for (std::size_t j = 1; j <= b.size(); ++j)
            {
                if (a[i - 1] == b[j - 1])
                {
                    current[j] = previous[j - 1] + 1;
                    best = (std::max)(best, current[j]);
                }
                else current[j] = 0;
            }
            std::swap(previous, current);
            std::fill(current.begin(), current.end(), 0);
        }
        return best;
    }

    [[nodiscard]] int LongestCommonSubsequence(std::wstring_view a, std::wstring_view b)
    {
        if (a.empty() || b.empty()) return 0;
        std::vector<int> previous(b.size() + 1);
        std::vector<int> current(b.size() + 1);
        for (std::size_t i = 1; i <= a.size(); ++i)
        {
            for (std::size_t j = 1; j <= b.size(); ++j)
            {
                current[j] = a[i - 1] == b[j - 1]
                    ? previous[j - 1] + 1
                    : (std::max)(previous[j], current[j - 1]);
            }
            std::swap(previous, current);
        }
        return previous[b.size()];
    }
}

namespace winforge::core::textanalysis
{
    TextStats AnalyzeTextStats(
        std::wstring_view text,
        bool ignoreStopWords,
        int topN) noexcept
    {
        TextStats result;
        try
        {
            if (topN < 1) topN = 1;
            result.characters = static_cast<int>(text.size());
            for (auto const value : text)
            {
                if (!IsManagedWhitespace(static_cast<std::uint16_t>(value)))
                {
                    ++result.charactersNoSpaces;
                }
            }

            auto const words = TokenizeTextStats(text);
            result.words = static_cast<int>(words.size());
            result.sentences = CountSentences(text);
            if (result.sentences == 0 && result.words > 0) result.sentences = 1;
            result.paragraphs = CountParagraphs(text);

            int totalWordCharacters{};
            std::vector<CountedTerm> unique;
            std::vector<CountedTerm> frequency;
            std::unordered_map<std::wstring, std::size_t> uniqueIndices;
            std::unordered_map<std::wstring, std::size_t> frequencyIndices;
            unique.reserve(words.size());
            frequency.reserve(words.size());
            uniqueIndices.reserve(words.size());
            frequencyIndices.reserve(words.size());
            auto const* stopWords = ignoreStopWords ? &TextStatsStopWordSet() : nullptr;
            for (auto const& word : words)
            {
                totalWordCharacters += static_cast<int>(word.size());
                result.syllables += SyllablesIn(word);
                auto const folded = FoldOrdinalIgnoreCase(word);
                AddOrdinalIgnoreCaseCount(unique, uniqueIndices, word, folded);
                if (!stopWords || !stopWords->contains(folded))
                {
                    AddOrdinalIgnoreCaseCount(frequency, frequencyIndices, word, folded);
                }
            }
            result.uniqueWords = static_cast<int>(unique.size());
            result.avgWordLength = result.words > 0
                ? static_cast<double>(totalWordCharacters) / result.words : 0.0;
            result.avgSentenceLength = result.sentences > 0
                ? static_cast<double>(result.words) / result.sentences : 0.0;
            result.readingMinutes = static_cast<double>(result.words) / 200.0;
            result.speakingMinutes = static_cast<double>(result.words) / 130.0;

            if (result.words > 0 && result.sentences > 0)
            {
                auto const wordsPerSentence =
                    static_cast<double>(result.words) / result.sentences;
                auto const syllablesPerWord =
                    static_cast<double>(result.syllables) / result.words;
                auto ease = 206.835 - 1.015 * wordsPerSentence - 84.6 * syllablesPerWord;
                auto grade = 0.39 * wordsPerSentence + 11.8 * syllablesPerWord - 15.59;
                result.fleschReadingEase = RoundToEven((std::clamp)(ease, -100.0, 121.0), 1);
                result.fleschKincaidGrade = RoundToEven((std::max)(0.0, grade), 1);
            }

            std::stable_sort(frequency.begin(), frequency.end(),
                [](CountedTerm const& left, CountedTerm const& right)
                {
                    if (left.count != right.count) return left.count > right.count;
                    return CompareFoldedOrdinal(left.folded, right.folded) < 0;
                });
            auto const take = (std::min)(static_cast<std::size_t>(topN), frequency.size());
            result.topWords.reserve(take);
            for (std::size_t index{}; index < take; ++index)
            {
                result.topWords.push_back({ frequency[index].term, frequency[index].count });
            }
        }
        catch (...)
        {
            return {};
        }
        return result;
    }

    std::wstring FormatDuration(double minutes) noexcept
    {
        try
        {
            if (minutes <= 0.0) return L"0s";
            auto rounded = std::nearbyint(minutes * 60.0);
            int totalSeconds{};
            if (std::isnan(rounded))
            {
                totalSeconds = 0;
            }
            else if (rounded >= static_cast<double>((std::numeric_limits<int>::max)()))
            {
                totalSeconds = (std::numeric_limits<int>::max)();
            }
            else if (rounded <= static_cast<double>((std::numeric_limits<int>::min)()))
            {
                totalSeconds = (std::numeric_limits<int>::min)();
            }
            else
            {
                totalSeconds = static_cast<int>(rounded);
            }
            if (totalSeconds < 1) totalSeconds = 1;
            auto const minutesPart = totalSeconds / 60;
            auto const secondsPart = totalSeconds % 60;
            if (minutesPart <= 0) return std::to_wstring(secondsPart) + L"s";
            wchar_t seconds[3]{};
            std::swprintf(seconds, std::size(seconds), L"%02d", secondsPart);
            return std::to_wstring(minutesPart) + L"m " + seconds + L"s";
        }
        catch (...)
        {
            return L"0s";
        }
    }

    WordFrequencyResult AnalyzeWordFrequency(
        std::wstring_view text,
        WordFrequencyOptions const& options) noexcept
    {
        WordFrequencyResult result;
        try
        {
            if (!HasNonWhitespace(text)) return result;
            std::vector<std::wstring> tokens;
            if (options.mode == FrequencyMode::Characters)
            {
                tokens = FrequencyCharacters(text, options.caseInsensitive);
            }
            else
            {
                auto words = FrequencyWords(text, options);
                if (options.mode == FrequencyMode::Bigrams)
                {
                    if (words.size() > 1) tokens.reserve(words.size() - 1);
                    for (std::size_t index{}; index + 1 < words.size(); ++index)
                    {
                        tokens.push_back(words[index] + L" " + words[index + 1]);
                    }
                }
                else
                {
                    tokens = std::move(words);
                }
            }
            if (tokens.empty()) return result;

            std::vector<CountedTerm> counts;
            std::unordered_map<std::wstring, std::size_t> indices;
            counts.reserve(tokens.size());
            indices.reserve(tokens.size());
            for (auto const& token : tokens) AddOrdinalCount(counts, indices, token);
            result.totalTokens = static_cast<int>(tokens.size());
            result.uniqueTokens = static_cast<int>(counts.size());
            result.diversity = static_cast<double>(result.uniqueTokens) / result.totalTokens;
            std::stable_sort(counts.begin(), counts.end(),
                [](CountedTerm const& left, CountedTerm const& right)
                {
                    if (left.count != right.count) return left.count > right.count;
                    return CompareCurrentCultureIgnoreCase(left.term, right.term) < 0;
                });

            auto const maximum = counts.front().count;
            result.rows.reserve(counts.size());
            int rank = 1;
            for (auto& entry : counts)
            {
                auto const fraction = maximum > 0
                    ? static_cast<double>(entry.count) / maximum : 0.0;
                auto const percentage = result.totalTokens > 0
                    ? static_cast<double>(entry.count) * 100.0 / result.totalTokens : 0.0;
                result.rows.push_back({
                    rank++, std::move(entry.term), entry.count,
                    (std::max)(2.0, fraction * 220.0),
                    FormatOneDecimal(percentage) + L"%"
                });
            }
        }
        catch (...)
        {
            // The managed oracle returns whatever was accumulated.
        }
        return result;
    }

    std::wstring ToWordFrequencyCsv(WordFrequencyResult const& result) noexcept
    {
        std::wstring csv;
        try
        {
            csv = L"Rank,Term,Count,Percent\r\n";
            for (auto const& row : result.rows)
            {
                csv.append(std::to_wstring(row.rank));
                csv.push_back(L',');
                csv.append(EscapeCsv(row.term));
                csv.push_back(L',');
                csv.append(std::to_wstring(row.count));
                csv.push_back(L',');
                csv.append(row.percent);
                csv.push_back(L'\n');
            }
        }
        catch (...)
        {
            // The managed oracle returns whatever was accumulated.
        }
        return csv;
    }

    StringComparisonMetrics ComputeStringComparison(
        std::wstring_view a,
        std::wstring_view b,
        bool ignoreCase,
        bool ignoreWhitespace) noexcept
    {
        try
        {
            auto const normalizedA = NormalizeComparison(a, ignoreCase, ignoreWhitespace);
            auto const normalizedB = NormalizeComparison(b, ignoreCase, ignoreWhitespace);
            StringComparisonMetrics result;
            result.lenA = static_cast<int>(normalizedA.size());
            result.lenB = static_cast<int>(normalizedB.size());
            result.truncated = normalizedA.size() > MaxStringCompareLength ||
                normalizedB.size() > MaxStringCompareLength;
            if (result.truncated)
            {
                result.levenshtein = -1;
                result.similarityPct = (std::numeric_limits<double>::quiet_NaN)();
                result.damerau = -1;
                result.longestCommonSubstring = -1;
                result.longestCommonSubsequence = -1;
            }
            else
            {
                result.levenshtein = Levenshtein(normalizedA, normalizedB);
                auto const maximum = (std::max)(normalizedA.size(), normalizedB.size());
                result.similarityPct = maximum == 0 ? 100.0 :
                    (1.0 - static_cast<double>(result.levenshtein) / maximum) * 100.0;
                result.damerau = DamerauLevenshtein(normalizedA, normalizedB);
                result.longestCommonSubstring = LongestCommonSubstring(normalizedA, normalizedB);
                result.longestCommonSubsequence = LongestCommonSubsequence(normalizedA, normalizedB);
            }
            result.hamming = normalizedA.size() == normalizedB.size()
                ? Hamming(normalizedA, normalizedB) : -1;
            result.jaroWinkler = JaroWinkler(normalizedA, normalizedB);
            return result;
        }
        catch (...)
        {
            return { 0, 0, false, -1,
                (std::numeric_limits<double>::quiet_NaN)(), -1, -1,
                (std::numeric_limits<double>::quiet_NaN)(), -1, -1 };
        }
    }

    std::wstring BuildStringComparisonReport(
        std::vector<std::pair<std::wstring, std::wstring>> const& rows) noexcept
    {
        try
        {
            std::wstring report;
            for (auto const& [label, value] : rows)
            {
                report.append(label);
                report.append(L": ");
                report.append(value);
                report.append(L"\r\n");
            }
            while (!report.empty() &&
                IsManagedWhitespace(static_cast<std::uint16_t>(report.back())))
            {
                report.pop_back();
            }
            return report;
        }
        catch (...)
        {
            return {};
        }
    }
}
